export const newRecipes = [
  // ---------------- IBA The Unforgettables 遗珠与历史名作 ----------------
  {
    id: 'white-lady',
    slug: 'white-lady',
    name: '白色佳人',
    nameEn: 'White Lady',
    category: 'classic',
    categoryZh: 'IBA 难忘经典',
    baseSpirit: 'Gin',
    baseSpiritZh: '金酒',
    flavorProfiles: ['柑橘系', '清爽系', '果香系'],
    flavorRadar: { sour: 4, sweet: 2, bitter: 1, strong: 3, fruity: 3, herbal: 2 },
    difficulty: 'medium',
    difficultyZh: '中等',
    glass: '碟形香槟杯 / Coupe Glass',
    garnish: '柠檬皮螺旋或杯口抹细糖边',
    ice: '摇荡滤冰 (Up)',
    technique: 'Shake',
    techniqueZh: '摇荡法',
    abv: 26,
    description: '金酒清脆的杜松子与君度橙皮油在鲜柠檬汁的激发下达到极其纯净的酸甜平衡，口感干爽明亮，如身着白裙的优雅名媛。',
    story: '1919年由伦敦传奇调酒师 Harry MacElhone 在 Ciro\'s 俱乐部创作，后在巴黎 Harry\'s New York Bar 完善定型为现代经典配方。',
    proTips: ['可加入少量蛋清进行 Dry Shake（干摇），使酒体表面形成一层如天鹅绒般细腻洁白的泡沫冠顶。'],
    image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=800&q=80',
    ingredients: [
      { name: '伦敦干金酒', nameEn: 'London Dry Gin', amountMl: 40, amountOz: '1 1/3 oz', rawId: 'gin' },
      { name: '君度橙酒', nameEn: 'Cointreau', amountMl: 30, amountOz: '1 oz', rawId: 'cointreau' },
      { name: '新鲜柠檬汁', nameEn: 'Fresh Lemon Juice', amountMl: 20, amountOz: '2/3 oz', rawId: 'fresh-lemon-juice' }
    ],
    steps: [
      '将碟形香槟杯预冷。',
      '在摇酒壶中加入所有原料及大量硬质方冰。',
      '剧烈摇荡 12-15 秒直至壶壁结霜。',
      '双重过滤（Fine Strain）倒入预冷杯中，喷拭柠檬皮精油。'
    ],
    isIbaCertified: true,
    ibaCategory: 'The Unforgettables'
  },
  {
    id: 'hanky-panky',
    slug: 'hanky-panky',
    name: '汉基帕基',
    nameEn: 'Hanky Panky',
    category: 'classic',
    categoryZh: 'IBA 难忘经典',
    baseSpirit: 'Gin',
    baseSpiritZh: '金酒',
    flavorProfiles: ['草本系', '苦系', '烈酒感'],
    flavorRadar: { sour: 1, sweet: 3, bitter: 4, strong: 4, fruity: 2, herbal: 5 },
    difficulty: 'easy',
    difficultyZh: '简单',
    glass: '尼克诺拉杯 / Nick & Nora Glass',
    garnish: '压榨橙皮卷',
    ice: '调和滤冰 (Up)',
    technique: 'Stir',
    techniqueZh: '调和法',
    abv: 28,
    description: '金酒与甜红苦艾酒的温润草本中，注入几滴费奈·布兰卡的神秘药草苦韵，瞬间赋予整杯酒摄人心魄的深度与悠长回甘。',
    story: '20世纪初由伦敦萨沃伊酒店（The Savoy）首位女性首席调酒师 Ada Coleman 为演员 Charles Hawtrey 创作，客人品尝后大呼“By Jove, Ada, that is the real hanky-panky!”。',
    proTips: ['费奈·布兰卡味道极其浓烈霸道，用量建议控制在 5~7.5ml，以免掩盖金酒的花香。'],
    image: 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?auto=format&fit=crop&w=800&q=80',
    ingredients: [
      { name: '伦敦干金酒', nameEn: 'London Dry Gin', amountMl: 45, amountOz: '1 1/2 oz', rawId: 'gin' },
      { name: '甜红苦艾酒', nameEn: 'Sweet Vermouth', amountMl: 45, amountOz: '1 1/2 oz', rawId: 'sweet-vermouth' },
      { name: '费奈·布兰卡苦酒', nameEn: 'Fernet-Branca', amountMl: 7.5, amountOz: '1/4 oz', rawId: 'fernet-branca' }
    ],
    steps: [
      '在调酒杯中加入所有原料与足量冰块。',
      '用吧勺匀速顺滑搅拌 30-45 秒直至充分冰镇与适度稀释。',
      '单层过滤倒入预冷的尼克诺拉杯中。',
      '在酒液表面喷挤橙皮精油并将橙皮悬挂杯缘。'
    ],
    isIbaCertified: true,
    ibaCategory: 'The Unforgettables'
  },
  {
    id: 'martinez',
    slug: 'martinez',
    name: '马天尼斯',
    nameEn: 'Martinez',
    category: 'classic',
    categoryZh: 'IBA 难忘经典',
    baseSpirit: 'Gin',
    baseSpiritZh: '金酒',
    flavorProfiles: ['草本系', '甜系', '烈酒感'],
    flavorRadar: { sour: 1, sweet: 3, bitter: 3, strong: 4, fruity: 3, herbal: 4 },
    difficulty: 'medium',
    difficultyZh: '中等',
    glass: '尼克诺拉杯 / Nick & Nora Glass',
    garnish: '马拉斯奇诺黑樱桃与柠檬皮卷',
    ice: '调和滤冰 (Up)',
    technique: 'Stir',
    techniqueZh: '调和法',
    abv: 30,
    description: '现代干马天尼与曼哈顿的共同始祖！老汤姆金酒的微甜圆润与红苦艾、黑樱桃利口酒交织出层次繁复的维多利亚时代复古芳香。',
    story: '收录于1887年调酒教父 Jerry Thomas 的经典著作，据传是在加州马丁内斯镇为淘金热时期的旅人所创。',
    proTips: ['制作正统马天尼斯务必选用老汤姆金酒（Old Tom Gin），其略带甜味的草本感是 Dry Gin 无法完全替代的。'],
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80',
    ingredients: [
      { name: '老汤姆金酒 (或优质干金酒)', nameEn: 'Old Tom Gin', amountMl: 45, amountOz: '1 1/2 oz', rawId: 'gin' },
      { name: '甜红苦艾酒', nameEn: 'Sweet Vermouth', amountMl: 45, amountOz: '1 1/2 oz', rawId: 'sweet-vermouth' },
      { name: '马拉斯奇诺黑樱桃利口酒', nameEn: 'Maraschino Liqueur', amountMl: 5, amountOz: '1 tsp', rawId: 'maraschino' },
      { name: '橙味苦精', nameEn: 'Orange Bitters', amountMl: 2, amountOz: '2 dashes', unit: '滴', rawId: 'orange-bitters' }
    ],
    steps: [
      '在调酒杯中加入所有配方与大量冰块。',
      '搅拌 30 秒至温度降至接近冰点。',
      '滤入冰镇鸡尾酒杯中。',
      '饰以一颗优质黑樱桃与柠檬皮精油。'
    ],
    isIbaCertified: true,
    ibaCategory: 'The Unforgettables'
  },
  {
    id: 'ramos-gin-fizz',
    slug: 'ramos-gin-fizz',
    name: '拉莫斯金菲士',
    nameEn: 'Ramos Gin Fizz',
    category: 'classic',
    categoryZh: 'IBA 难忘经典',
    baseSpirit: 'Gin',
    baseSpiritZh: '金酒',
    flavorProfiles: ['奶香系', '柑橘系', '清爽系'],
    flavorRadar: { sour: 3, sweet: 3, bitter: 0, strong: 2, fruity: 2, herbal: 3 },
    difficulty: 'advanced',
    difficultyZh: '大师级',
    glass: '柯林杯 / Collins Glass',
    garnish: '无（自然升腾立起 2cm 坚挺奶沫柱）',
    ice: '无冰伺服 (Chilled No Ice)',
    technique: 'Shake',
    techniqueZh: '超长干摇与湿摇',
    abv: 12,
    description: '调酒界的珠穆朗玛峰！金酒、奶油、蛋清、柑橘与橙花水在极致摇荡下乳化成如舒芙蕾般挺立的丝滑云朵泡沫，口感如丝绒冰淇淋。',
    story: '1888年由 Henry C. Ramos 在新奥尔良 Imperial Cabinet 酒吧发明，当时酒吧雇用数十名“摇酒男孩”接力摇晃12分钟之久。',
    proTips: ['先不加冰干摇（Dry Shake）至少1分钟充分乳化蛋白质，加冰湿摇后倒入杯中静置1分钟，再从杯底缓缓注入冰苏打水顶起泡沫柱。'],
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80',
    ingredients: [
      { name: '伦敦干金酒', nameEn: 'London Dry Gin', amountMl: 45, amountOz: '1 1/2 oz', rawId: 'gin' },
      { name: '新鲜青柠汁', nameEn: 'Fresh Lime Juice', amountMl: 15, amountOz: '1/2 oz', rawId: 'fresh-lime-juice' },
      { name: '新鲜柠檬汁', nameEn: 'Fresh Lemon Juice', amountMl: 15, amountOz: '1/2 oz', rawId: 'fresh-lemon-juice' },
      { name: '单糖浆', nameEn: 'Simple Syrup', amountMl: 30, amountOz: '1 oz', rawId: 'simple-syrup' },
      { name: '动物性淡奶油', nameEn: 'Heavy Cream', amountMl: 60, amountOz: '2 oz', rawId: 'heavy-cream' },
      { name: '新鲜蛋清', nameEn: 'Fresh Egg White', amountMl: 30, amountOz: '1 egg white', rawId: 'egg-white' },
      { name: '天然橙花水', nameEn: 'Orange Flower Water', amountMl: 1, amountOz: '3 drops', unit: '滴', rawId: 'orange-flower-water' },
      { name: '强气泡苏打水', nameEn: 'Club Soda', amountMl: 45, amountOz: '1 1/2 oz', rawId: 'club-soda' }
    ],
    steps: [
      '在摇酒壶中加入金酒、酸汁、糖浆、淡奶油、蛋清和橙花水（先不加冰）。',
      '极高频率干摇 60 秒直至完全乳化细腻发白。',
      '加入满壶方冰，继续高强度摇荡 60 秒至极致冰冷。',
      '滤入未加冰的冰镇柯林杯中，放入冰箱冷藏静置 2 分钟让泡沫凝固。',
      '用吧勺引流，从杯中心缓缓倒入冰苏打水，将蛋白奶沫直立顶出杯口 2 厘米。'
    ],
    isIbaCertified: true,
    ibaCategory: 'The Unforgettables'
  },
  {
    id: 'vieux-carre',
    slug: 'vieux-carre',
    name: '老广场',
    nameEn: 'Vieux Carré',
    category: 'classic',
    categoryZh: 'IBA 难忘经典',
    baseSpirit: 'Whiskey',
    baseSpiritZh: '威士忌/白兰地',
    flavorProfiles: ['烈酒感', '草本系', '甜系'],
    flavorRadar: { sour: 0, sweet: 3, bitter: 3, strong: 5, fruity: 2, herbal: 4 },
    difficulty: 'medium',
    difficultyZh: '中等',
    glass: '古典杯 / Rocks Glass',
    garnish: '压榨柠檬皮卷与黑樱桃',
    ice: '整块大方冰',
    technique: 'Stir',
    techniqueZh: '调和法',
    abv: 33,
    description: '新奥尔良法式区的灵魂赞歌！黑麦威士忌的辛辣与干邑的圆润在甜苦艾、法国廊酒和双重苦精中融为一体，浑厚深沉，回味无尽。',
    story: '1938年由新奥尔良著名的 Monteleone 酒店旋转酒吧首席调酒师 Walter Bergeron 创作，致敬新奥尔良历史悠久的“老广场（法式区）”。',
    proTips: ['贝乔苦精（Peychaud\'s）与安哥斯图拉苦精（Angostura）各一滴是原版灵魂，缺一不可。'],
    image: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?auto=format&fit=crop&w=800&q=80',
    ingredients: [
      { name: '黑麦威士忌', nameEn: 'Rye Whiskey', amountMl: 30, amountOz: '1 oz', rawId: 'whiskey-rye' },
      { name: '干邑白兰地', nameEn: 'Cognac VSOP', amountMl: 30, amountOz: '1 oz', rawId: 'brandy-cognac' },
      { name: '甜红苦艾酒', nameEn: 'Sweet Vermouth', amountMl: 30, amountOz: '1 oz', rawId: 'sweet-vermouth' },
      { name: '法国廊酒 (Bénédictine)', nameEn: 'DOM Bénédictine', amountMl: 5, amountOz: '1 tsp', rawId: 'benedictine' },
      { name: '贝乔苦精', nameEn: 'Peychaud\'s Bitters', amountMl: 1, amountOz: '1 dash', unit: '滴', rawId: 'peychauds-bitters' },
      { name: '安哥斯图拉苦精', nameEn: 'Angostura Bitters', amountMl: 1, amountOz: '1 dash', unit: '滴', rawId: 'angostura-bitters' }
    ],
    steps: [
      '在调酒杯中加入所有配料与冰块。',
      '匀速搅拌 35-40 秒直至酒体冰凉且达到理想稀释度。',
      '滤入放有整颗手凿大方冰的古典杯中。',
      '喷挤柠檬皮精油并饰以鸡尾酒黑樱桃。'
    ],
    isIbaCertified: true,
    ibaCategory: 'The Unforgettables'
  },
  {
    id: 'brandy-alexander',
    slug: 'brandy-alexander',
    name: '白兰地亚历山大',
    nameEn: 'Brandy Alexander',
    category: 'classic',
    categoryZh: 'IBA 难忘经典',
    baseSpirit: 'Brandy',
    baseSpiritZh: '白兰地',
    flavorProfiles: ['奶香系', '甜系', '烈酒感'],
    flavorRadar: { sour: 0, sweet: 4, bitter: 1, strong: 3, fruity: 1, herbal: 2 },
    difficulty: 'easy',
    difficultyZh: '简单',
    glass: '碟形香槟杯 / Coupe Glass',
    garnish: '现磨肉豆蔻粉 (Fresh Nutmeg)',
    ice: '摇荡滤冰 (Up)',
    technique: 'Shake',
    techniqueZh: '摇荡法',
    abv: 20,
    description: '干邑白兰地的优雅木香与棕可可利口酒、浓郁鲜奶油三者等比例交融，顶层肉豆蔻辛香点缀，如同一杯盛在酒杯中的成人液体巧克力慕斯。',
    story: '起源于20世纪初纽约，早先以金酒制作（Alexander #1），后发展出干邑白兰地版并因披头士约翰·列侬等名流的由衷喜爱而名扬全球。',
    proTips: ['杯顶现磨的肉豆蔻粉是这杯酒的嗅觉画龙点睛之笔，切勿使用现成瓶装粉末。'],
    image: 'https://images.unsplash.com/photo-1550985616-10810253b84d?auto=format&fit=crop&w=800&q=80',
    ingredients: [
      { name: '干邑白兰地', nameEn: 'Cognac', amountMl: 30, amountOz: '1 oz', rawId: 'brandy-cognac' },
      { name: '棕可可利口酒 (或白可可)', nameEn: 'Crème de Cacao Brown', amountMl: 30, amountOz: '1 oz', rawId: 'creme-de-cacao' },
      { name: '新鲜淡奶油', nameEn: 'Fresh Heavy Cream', amountMl: 30, amountOz: '1 oz', rawId: 'heavy-cream' }
    ],
    steps: [
      '在摇酒壶中倒入干邑、可可利口酒与新鲜淡奶油。',
      '加满方冰，剧烈摇荡 15 秒使奶油与酒液彻底乳化并迅速冷却。',
      '双重过滤倒入预冷碟形香槟杯。',
      '在奶白色的泡沫表面用刨刀现磨少量新鲜肉豆蔻碎。'
    ],
    isIbaCertified: true,
    ibaCategory: 'The Unforgettables'
  },
  {
    id: 'between-the-sheets',
    slug: 'between-the-sheets',
    name: '床笫之间',
    nameEn: 'Between the Sheets',
    category: 'classic',
    categoryZh: 'IBA 难忘经典',
    baseSpirit: 'Brandy',
    baseSpiritZh: '白兰地/朗姆',
    flavorProfiles: ['柑橘系', '烈酒感', '果香系'],
    flavorRadar: { sour: 3, sweet: 2, bitter: 0, strong: 4, fruity: 3, herbal: 1 },
    difficulty: 'medium',
    difficultyZh: '中等',
    glass: '马天尼杯 / Martini Glass',
    garnish: '压榨柠檬皮',
    ice: '摇荡滤冰 (Up)',
    technique: 'Shake',
    techniqueZh: '摇荡法',
    abv: 31,
    description: '边车（Sidecar）的热烈升级版！白兰地的醇厚遇上加勒比白朗姆的野性甘甜，君度与柠檬汁穿针引线，酸冽干脆，充满诱惑力。',
    story: '1930年代由巴黎 Harry\'s New York Bar 的 Harry MacElhone 创作，因其强劲酒力与暧昧动人的名字迅速风靡欧美名流圈。',
    proTips: ['选用陈年 3 年以上的优质加勒比白朗姆与 VSOP 干邑，能让果酸与木质调达到天衣无缝的交融。'],
    image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=800&q=80',
    ingredients: [
      { name: '干邑白兰地', nameEn: 'Cognac', amountMl: 30, amountOz: '1 oz', rawId: 'brandy-cognac' },
      { name: '白朗姆酒', nameEn: 'White Rum', amountMl: 30, amountOz: '1 oz', rawId: 'rum-white' },
      { name: '君度橙酒', nameEn: 'Cointreau', amountMl: 30, amountOz: '1 oz', rawId: 'cointreau' },
      { name: '新鲜柠檬汁', nameEn: 'Fresh Lemon Juice', amountMl: 20, amountOz: '2/3 oz', rawId: 'fresh-lemon-juice' }
    ],
    steps: [
      '在摇酒壶中加入所有成分与硬冰块。',
      '有力摇荡 12 秒至壶身凝结厚白霜。',
      '细网双重过滤倒入预冷马天尼杯。',
      '轻喷柠檬皮精油后弃去果皮或扭卷装饰。'
    ],
    isIbaCertified: true,
    ibaCategory: 'The Unforgettables'
  },
  {
    id: 'rusty-nail',
    slug: 'rusty-nail',
    name: '生锈钉',
    nameEn: 'Rusty Nail',
    category: 'classic',
    categoryZh: 'IBA 难忘经典',
    baseSpirit: 'Whiskey',
    baseSpiritZh: '威士忌',
    flavorProfiles: ['烈酒感', '甜系', '草本系'],
    flavorRadar: { sour: 0, sweet: 4, bitter: 1, strong: 5, fruity: 2, herbal: 3 },
    difficulty: 'easy',
    difficultyZh: '简单',
    glass: '古典杯 / Rocks Glass',
    garnish: '压榨柠檬皮卷',
    ice: '大块老冰',
    technique: 'Build',
    techniqueZh: '直调法 / 调和',
    abv: 38,
    description: '苏格兰威士忌的硬朗麦芽烟熏与杜林标的石楠花蜂蜜、草药香料在冰块融化中逐渐交融，口感甘醇厚实，如铁锈钉子般坚毅深刻。',
    story: '1960年代在纽约著名的 21 俱乐部广受著名好莱坞明星团体“鼠党（Rat Pack）”推崇，成为硬汉威士忌调酒的代名词。',
    proTips: ['威士忌与杜林标的经典比例为 2:1 或 3:1，追求更干爽口感可选用泥煤风味苏格兰威士忌。'],
    image: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?auto=format&fit=crop&w=800&q=80',
    ingredients: [
      { name: '苏格兰调和威士忌', nameEn: 'Blended Scotch Whisky', amountMl: 45, amountOz: '1 1/2 oz', rawId: 'whiskey-scotch' },
      { name: '杜林标蜂蜜威士忌利口酒', nameEn: 'Drambuie', amountMl: 25, amountOz: '3/4 oz', rawId: 'drambuie' }
    ],
    steps: [
      '在古典杯中放入大块晶莹剔透的老冰。',
      '依序倒入苏格兰威士忌与杜林标利口酒。',
      '用吧勺轻轻搅拌 15 秒使酒液与冰块充分融合。',
      '在杯口喷挤一片柠檬皮精油。'
    ],
    isIbaCertified: true,
    ibaCategory: 'The Unforgettables'
  },
  {
    id: 'rob-roy',
    slug: 'rob-roy',
    name: '罗伯罗伊',
    nameEn: 'Rob Roy',
    category: 'classic',
    categoryZh: 'IBA 难忘经典',
    baseSpirit: 'Whiskey',
    baseSpiritZh: '威士忌',
    flavorProfiles: ['烈酒感', '草本系', '苦系'],
    flavorRadar: { sour: 0, sweet: 3, bitter: 3, strong: 4, fruity: 2, herbal: 3 },
    difficulty: 'easy',
    difficultyZh: '简单',
    glass: '尼克诺拉杯 / Nick & Nora Glass',
    garnish: '马拉斯奇诺黑樱桃',
    ice: '调和滤冰 (Up)',
    technique: 'Stir',
    techniqueZh: '调和法',
    abv: 31,
    description: '苏格兰版的曼哈顿！以苏格兰威士忌代替美国黑麦威士忌，赋予整杯酒更深沉的石楠花蜜、烟熏橡木与甜红苦艾的华丽草本。',
    story: '1894年纽约华尔道夫酒店调酒师为庆祝同名轻歌剧《罗伯·罗伊》（致敬苏格兰罗宾汉式的民族英雄）首演而创。',
    proTips: ['选用带有轻微泥煤烟熏的苏格兰调和威士忌，搭配 Carpano Antica 级高品质甜苦艾，风味尤为惊艳。'],
    image: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?auto=format&fit=crop&w=800&q=80',
    ingredients: [
      { name: '苏格兰威士忌', nameEn: 'Scotch Whisky', amountMl: 50, amountOz: '1 2/3 oz', rawId: 'whiskey-scotch' },
      { name: '甜红苦艾酒', nameEn: 'Sweet Vermouth', amountMl: 25, amountOz: '3/4 oz', rawId: 'sweet-vermouth' },
      { name: '安哥斯图拉芳香苦精', nameEn: 'Angostura Bitters', amountMl: 2, amountOz: '2 dashes', unit: '滴', rawId: 'angostura-bitters' }
    ],
    steps: [
      '在调酒杯中加入苏格兰威士忌、甜红苦艾与苦精。',
      '加满冰块，轻柔平稳搅拌 30 秒。',
      '滤入冰镇的尼克诺拉杯或马天尼杯中。',
      '放入一颗马拉斯奇诺黑樱桃沉底。'
    ],
    isIbaCertified: true,
    ibaCategory: 'The Unforgettables'
  },
  {
    id: 'blood-and-sand',
    slug: 'blood-and-sand',
    name: '血与沙',
    nameEn: 'Blood and Sand',
    category: 'classic',
    categoryZh: 'IBA 难忘经典',
    baseSpirit: 'Whiskey',
    baseSpiritZh: '威士忌',
    flavorProfiles: ['果香系', '甜系', '烟熏系'],
    flavorRadar: { sour: 2, sweet: 3, bitter: 2, strong: 3, fruity: 4, herbal: 2 },
    difficulty: 'medium',
    difficultyZh: '中等',
    glass: '碟形香槟杯 / Coupe Glass',
    garnish: '压榨橙皮卷',
    ice: '摇荡滤冰 (Up)',
    technique: 'Shake',
    techniqueZh: '摇荡法',
    abv: 22,
    description: '极为罕见的四种原料等比例结构！苏格兰威士忌的泥煤烟熏、樱桃利口酒的深红如血、甜苦艾的草本与鲜橙汁的明媚金沙完美平衡。',
    story: '诞生于1922年，灵感源自鲁道夫·瓦伦蒂诺主演的经典斗牛士无声电影《血与沙》（Blood and Sand）。',
    proTips: ['橙汁务必使用新鲜现榨甜橙汁并双重过滤，泥煤威士忌能极大提升层次感。'],
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80',
    ingredients: [
      { name: '苏格兰威士忌 (带轻度泥煤)', nameEn: 'Scotch Whisky', amountMl: 25, amountOz: '3/4 oz', rawId: 'whiskey-scotch' },
      { name: '希灵樱桃利口酒 (Cherry Heering)', nameEn: 'Cherry Heering Liqueur', amountMl: 25, amountOz: '3/4 oz', rawId: 'maraschino' },
      { name: '甜红苦艾酒', nameEn: 'Sweet Vermouth', amountMl: 25, amountOz: '3/4 oz', rawId: 'sweet-vermouth' },
      { name: '新鲜现榨甜橙汁', nameEn: 'Fresh Orange Juice', amountMl: 25, amountOz: '3/4 oz', rawId: 'fresh-orange-juice' }
    ],
    steps: [
      '在摇酒壶中加入四种等比例原料与冰块。',
      '剧烈摇荡 12-15 秒直至充分冷却。',
      '双重过滤倒入预冷的碟形香槟杯中。',
      '在酒液上方挤压橙皮精油后悬于杯缘。'
    ],
    isIbaCertified: true,
    ibaCategory: 'The Unforgettables'
  },
  {
    id: 'gibson',
    slug: 'gibson',
    name: '吉普森',
    nameEn: 'Gibson',
    category: 'classic',
    categoryZh: 'IBA 难忘经典',
    baseSpirit: 'Gin',
    baseSpiritZh: '金酒',
    flavorProfiles: ['清爽系', '烈酒感', '草本系'],
    flavorRadar: { sour: 0, sweet: 0, bitter: 2, strong: 5, fruity: 0, herbal: 4 },
    difficulty: 'easy',
    difficultyZh: '简单',
    glass: '马天尼杯 / Martini Glass',
    garnish: '鸡尾酒珍珠洋葱两颗 (Cocktail Onion)',
    ice: '调和滤冰 (Up)',
    technique: 'Stir',
    techniqueZh: '调和法',
    abv: 35,
    description: '马天尼家族中最具神秘咸鲜气息的贵族变体！用爽脆微咸的珍珠小洋葱替代橄榄与柠檬皮，带出金酒纯粹凛冽的植物矿物风味。',
    story: '1930年代插画大师 Charles Dana Gibson 在纽约 The Players 俱乐部要求调酒师 Charley Connolly 为他制作一杯与众不同的干马天尼，由此诞生。',
    proTips: ['珍珠洋葱的微量盐水浸汁会随着时间渗入酒液中，带来极其微妙的鲜美回甘。'],
    image: 'https://images.unsplash.com/photo-1527061011665-3652c757a4d4?auto=format&fit=crop&w=800&q=80',
    ingredients: [
      { name: '伦敦干金酒', nameEn: 'London Dry Gin', amountMl: 60, amountOz: '2 oz', rawId: 'gin' },
      { name: '干苦艾酒', nameEn: 'Dry Vermouth', amountMl: 10, amountOz: '1/3 oz', rawId: 'dry-vermouth' },
      { name: '鸡尾酒珍珠小洋葱', nameEn: 'Cocktail Silverskin Onion', amountMl: 2, amountOz: '2 onions', unit: '颗', rawId: 'cocktail-onion' }
    ],
    steps: [
      '在调酒杯中加入干金酒与干苦艾酒。',
      '加入满杯硬质方冰，顺滑搅拌 30 秒至极度冰镇。',
      '滤入冷冻至结霜的马天尼杯中。',
      '用鸡尾酒竹签串入 1~2 颗珍珠洋葱沉入杯底。'
    ],
    isIbaCertified: true,
    ibaCategory: 'The Unforgettables'
  },
  {
    id: 'corpse-reviver-2',
    slug: 'corpse-reviver-2',
    name: '除虫剂2号 / 尸体复活者2号',
    nameEn: 'Corpse Reviver #2',
    category: 'contemporary',
    categoryZh: 'IBA 当代经典',
    baseSpirit: 'Gin',
    baseSpiritZh: '金酒',
    flavorProfiles: ['柑橘系', '草本系', '清爽系'],
    flavorRadar: { sour: 4, sweet: 2, bitter: 1, strong: 3, fruity: 3, herbal: 4 },
    difficulty: 'medium',
    difficultyZh: '中等',
    glass: '碟形香槟杯 / Coupe Glass',
    garnish: '压榨柠檬皮卷',
    ice: '摇荡滤冰 (Up)',
    technique: 'Shake',
    techniqueZh: '摇荡法与苦艾润杯',
    abv: 26,
    description: '传奇解酒醒脑“回魂酒”！金酒、君度、丽叶白开胃酒与鲜柠檬汁四等分完美平衡，杯壁一层幽微的苦艾酒喷雾带来画龙点睛的八角草本芬芳。',
    story: '1930年由 Harry Craddock 记录于《The Savoy Cocktail Book》，书中名言：“连喝四杯后，连尸体都会重新复活”。',
    proTips: ['苦艾酒只需在杯中涮一圈或用喷雾瓶喷洒杯壁即可，过量会掩盖丽叶白的柑橘花香。'],
    image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=800&q=80',
    ingredients: [
      { name: '伦敦干金酒', nameEn: 'London Dry Gin', amountMl: 22.5, amountOz: '3/4 oz', rawId: 'gin' },
      { name: '君度橙酒', nameEn: 'Cointreau', amountMl: 22.5, amountOz: '3/4 oz', rawId: 'cointreau' },
      { name: '丽叶白开胃酒 (Lillet Blanc)', nameEn: 'Lillet Blanc', amountMl: 22.5, amountOz: '3/4 oz', rawId: 'lillet-blanc' },
      { name: '新鲜柠檬汁', nameEn: 'Fresh Lemon Juice', amountMl: 22.5, amountOz: '3/4 oz', rawId: 'fresh-lemon-juice' },
      { name: '苦艾酒 (润杯喷雾)', nameEn: 'Absinthe', amountMl: 2, amountOz: 'Rinse / Spray', unit: '润杯', rawId: 'absinthe' }
    ],
    steps: [
      '在冰镇碟形杯内壁倒入少许苦艾酒转动润杯（或喷雾喷洒）后倒出多余酒液。',
      '在摇酒壶中加入金酒、君度、丽叶白与新鲜柠檬汁。',
      '加满冰块强力摇荡 12 秒。',
      '双重过滤倒入准备好的杯中，喷拭柠檬皮精油。'
    ],
    isIbaCertified: true,
    ibaCategory: 'Contemporary Classics'
  },
  {
    id: 'vesper-martini',
    slug: 'vesper-martini',
    name: '皇家赌场维斯帕马天尼',
    nameEn: 'Vesper Martini',
    category: 'contemporary',
    categoryZh: 'IBA 当代经典',
    baseSpirit: 'Gin',
    baseSpiritZh: '金酒/伏特加',
    flavorProfiles: ['烈酒感', '清爽系', '草本系'],
    flavorRadar: { sour: 0, sweet: 1, bitter: 2, strong: 5, fruity: 1, herbal: 3 },
    difficulty: 'medium',
    difficultyZh: '中等',
    glass: '碟形香槟杯 / Coupe Glass',
    garnish: '大片柠檬皮螺旋',
    ice: '摇荡滤冰 (Up)',
    technique: 'Shake',
    techniqueZh: '摇荡法 (Shaken, Not Stirred)',
    abv: 38,
    description: '007 詹姆斯·邦德专属定制鸡尾酒！三份金酒、一份伏特加与半份丽叶白，经冰块极速剧烈摇晃，冷冽通透，直击心灵。',
    story: '伊恩·弗莱明在1953年第一部邦德小说《皇家赌场》中创造，邦德以他一生挚爱的双重间谍女主角维斯帕·琳德（Vesper Lynd）为其命名。',
    proTips: ['摇荡法会让微小冰晶融入酒体，带来邦德追求的“极冷且如丝绸般薄脆”的独特口感。'],
    image: 'https://images.unsplash.com/photo-1527061011665-3652c757a4d4?auto=format&fit=crop&w=800&q=80',
    ingredients: [
      { name: '伦敦干金酒 (如添加利或哥顿)', nameEn: 'London Dry Gin', amountMl: 45, amountOz: '1 1/2 oz', rawId: 'gin' },
      { name: '纯净伏特加', nameEn: 'Vodka', amountMl: 15, amountOz: '1/2 oz', rawId: 'vodka' },
      { name: '丽叶白开胃酒 (Lillet Blanc)', nameEn: 'Lillet Blanc', amountMl: 7.5, amountOz: '1/4 oz', rawId: 'lillet-blanc' }
    ],
    steps: [
      '在摇酒壶中注入金酒、伏特加与丽叶白。',
      '加满极冷硬冰块，按邦德要求“极速且用力摇荡直至完全冰透”。',
      '双重过滤倒入深碟形香槟杯中。',
      '削一片宽薄柠檬皮，在酒面上挤出精油后优雅滑入杯中。'
    ],
    isIbaCertified: true,
    ibaCategory: 'Contemporary Classics'
  },
  {
    id: 'pisco-sour',
    slug: 'pisco-sour',
    name: '皮斯科酸',
    nameEn: 'Pisco Sour',
    category: 'contemporary',
    categoryZh: 'IBA 当代经典',
    baseSpirit: 'Brandy',
    baseSpiritZh: '皮斯科白兰地',
    flavorProfiles: ['柑橘系', '果香系', '清爽系'],
    flavorRadar: { sour: 4, sweet: 3, bitter: 1, strong: 3, fruity: 4, herbal: 1 },
    difficulty: 'medium',
    difficultyZh: '中等',
    glass: '古典杯 / Rocks Glass',
    garnish: '表面点缀 3 滴安哥斯图拉苦精',
    ice: '摇荡滤冰 (Up)',
    technique: 'Shake',
    techniqueZh: '反向双重摇荡法',
    abv: 22,
    description: '秘鲁与智利的南美洲国饮！皮斯科清新的白葡萄与茉莉花香，与鲜青柠汁、蛋清乳化出厚实绵密的云朵泡沫，表面苦精滴点香气高雅。',
    story: '1920年代由美国调酒师 Victor Morris 在秘鲁利马的 Morris Bar 创造，后成为南美最具代表性的全球文化遗产鸡尾酒。',
    proTips: ['秘鲁经典黄金比例为 3:1:1（60ml 皮斯科、20ml 青柠汁、20ml 单糖浆），表面滴入3滴苦精可中和蛋清腥气并增添视觉美感。'],
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80',
    ingredients: [
      { name: '秘鲁皮斯科白兰地', nameEn: 'Peruvian Pisco (Quebranta)', amountMl: 60, amountOz: '2 oz', rawId: 'pisco' },
      { name: '新鲜青柠汁', nameEn: 'Fresh Lime Juice', amountMl: 30, amountOz: '1 oz', rawId: 'fresh-lime-juice' },
      { name: '单糖浆', nameEn: 'Simple Syrup', amountMl: 20, amountOz: '2/3 oz', rawId: 'simple-syrup' },
      { name: '新鲜蛋清', nameEn: 'Fresh Egg White', amountMl: 20, amountOz: '1 egg white', rawId: 'egg-white' },
      { name: '安哥斯图拉芳香苦精', nameEn: 'Angostura Bitters', amountMl: 1, amountOz: '3 drops', unit: '滴', rawId: 'angostura-bitters' }
    ],
    steps: [
      '将皮斯科、青柠汁、糖浆与蛋清倒入摇酒壶中（不加冰）。',
      '干摇 15 秒打发蛋清形成细腻泡沫。',
      '加入大量方冰，强力湿摇 15 秒至极冷。',
      '双重过滤倒入预冷古典杯或笛形杯中。',
      '在顶部奶白色的致密泡沫上，滴下 3 滴安哥斯图拉苦精并用牙签拉花。'
    ],
    isIbaCertified: true,
    ibaCategory: 'Contemporary Classics'
  },
  {
    id: 'caipirinha',
    slug: 'caipirinha',
    name: '卡匹林哈',
    nameEn: 'Caipirinha',
    category: 'contemporary',
    categoryZh: 'IBA 当代经典',
    baseSpirit: 'Rum',
    baseSpiritZh: '卡夏莎甘蔗酒',
    flavorProfiles: ['柑橘系', '清爽系', '果香系'],
    flavorRadar: { sour: 4, sweet: 3, bitter: 1, strong: 3, fruity: 3, herbal: 2 },
    difficulty: 'easy',
    difficultyZh: '简单',
    glass: '古典杯 / Rocks Glass',
    garnish: '压碎青柠块与甘蔗糖棒',
    ice: '满杯碎冰 (Crushed Ice)',
    technique: 'Muddle',
    techniqueZh: '捣压压榨法 (Muddle & Build)',
    abv: 25,
    description: '巴西激情与阳光的化身！整颗新鲜青柠块与蔗糖在杯底强力捣压，释放大量天然青柠皮精油与酸爽果汁，倒入卡夏莎与碎冰，原始狂野、鲜活多汁。',
    story: '起源于巴西圣保罗乡村，原本作为预防流感的传统草药饮品，后演化为巴西法定国酒鸡尾酒。',
    proTips: ['青柠务必去白瓤切块，用力捣出皮油但不要过度研磨苦皮；使用粗粒原蔗糖（Cane Sugar）风味最地道。'],
    image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=800&q=80',
    ingredients: [
      { name: '巴西卡夏莎甘蔗酒 (Cachaça)', nameEn: 'Cachaça', amountMl: 60, amountOz: '2 oz', rawId: 'cachaca' },
      { name: '新鲜青柠', nameEn: 'Fresh Lime (cut into wedges)', amountMl: 1, amountOz: '1 whole lime', unit: '整颗', rawId: 'fresh-lime-juice' },
      { name: '粗粒白砂糖 (或单糖浆)', nameEn: 'Cane Sugar', amountMl: 15, amountOz: '2 tsp', unit: '茶匙', rawId: 'simple-syrup' }
    ],
    steps: [
      '将一颗青柠切成 8 瓣小块，放入古典杯底。',
      '加入 2 茶匙细砂糖。',
      '用捣棒（Muddler）用力捣压青柠，挤出全部果汁并充分压出皮油。',
      '在杯中填满碎冰或方冰。',
      '注入 60ml 卡夏莎甘蔗酒，用吧勺自底向上充分搅拌提拉。'
    ],
    isIbaCertified: true,
    ibaCategory: 'Contemporary Classics'
  },
  {
    id: 'mint-julep',
    slug: 'mint-julep',
    name: '薄荷朱利普',
    nameEn: 'Mint Julep',
    category: 'contemporary',
    categoryZh: 'IBA 当代经典',
    baseSpirit: 'Whiskey',
    baseSpiritZh: '波本威士忌',
    flavorProfiles: ['清爽系', '烈酒感', '甜系'],
    flavorRadar: { sour: 0, sweet: 3, bitter: 0, strong: 5, fruity: 1, herbal: 4 },
    difficulty: 'easy',
    difficultyZh: '简单',
    glass: '铜制马克杯 / Copper Mule Mug',
    garnish: '巨大薄荷枝顶冠与撒糖粉',
    ice: '雪山状压实碎冰 (Packed Crushed Ice)',
    technique: 'Muddle',
    techniqueZh: '捣叶调和法',
    abv: 32,
    description: '美国南部贵族与肯塔基德比马术大赛的标志！波本威士忌的焦糖橡木香在冰霜银杯与沁凉鲜薄荷的包裹下散发极致冰爽，杯壁结霜如银雪。',
    story: '18世纪流行于美国弗吉尼亚与肯塔基州，自1938年起成为肯塔基德比大赛（Kentucky Derby）官方指定饮品，每年两天内消耗超12万杯。',
    proTips: ['薄荷叶只需轻轻按压萃取精油，不可捣碎叶脉产生苦涩叶绿素；务必将银杯/金属杯搅拌至外壁凝结白霜。'],
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
    ingredients: [
      { name: '肯塔基波本威士忌', nameEn: 'Kentucky Straight Bourbon Whiskey', amountMl: 60, amountOz: '2 oz', rawId: 'whiskey-bourbon' },
      { name: '新鲜薄荷嫩枝与叶片', nameEn: 'Fresh Mint Leaves', amountMl: 8, amountOz: '8-10 leaves', unit: '片', rawId: 'fresh-mint' },
      { name: '单糖浆 (或细砂糖)', nameEn: 'Simple Syrup', amountMl: 10, amountOz: '1/3 oz', rawId: 'simple-syrup' }
    ],
    steps: [
      '在金属 Julep 杯底放入薄荷叶与糖浆。',
      '用吧勺轻柔按压薄荷叶释放芬芳香油。',
      '倒入 30ml 波本威士忌并加入半杯碎冰，快速搅拌。',
      '再注入剩余 30ml 波本威士忌，将碎冰填至高出杯口堆成雪山状。',
      '拍醒一大束新鲜薄荷插在冰顶，在薄荷叶上洒少许糖粉装饰。'
    ],
    isIbaCertified: true,
    ibaCategory: 'Contemporary Classics'
  },
  {
    id: 'grasshopper',
    slug: 'grasshopper',
    name: '绿色蚱蜢',
    nameEn: 'Grasshopper',
    category: 'contemporary',
    categoryZh: 'IBA 当代经典',
    baseSpirit: 'Liqueur',
    baseSpiritZh: '利口酒',
    flavorProfiles: ['奶香系', '甜系', '草本系'],
    flavorRadar: { sour: 0, sweet: 5, bitter: 0, strong: 2, fruity: 0, herbal: 3 },
    difficulty: 'easy',
    difficultyZh: '简单',
    glass: '碟形香槟杯 / Coupe Glass',
    garnish: '薄荷嫩叶与黑巧克力碎屑',
    ice: '摇荡滤冰 (Up)',
    technique: 'Shake',
    techniqueZh: '摇荡法',
    abv: 16,
    description: '梦幻薄荷绿色的经典甜点鸡尾酒！绿薄荷利口酒的冰凉透彻、白可可利口酒的甜香与鲜奶油交织出如同薄荷巧克力冰淇淋般的醇美滋味。',
    story: '1918年由新奥尔良著名餐厅 Tujague\'s 的老板 Philip Guichet 创作并在纽约鸡尾酒大赛中获奖。',
    proTips: ['三种原料严格按 1:1:1 比例调配，充分剧烈摇荡至奶油完全发泡细腻。'],
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80',
    ingredients: [
      { name: '绿薄荷利口酒', nameEn: 'Green Crème de Menthe', amountMl: 30, amountOz: '1 oz', rawId: 'creme-de-menthe' },
      { name: '白可可利口酒', nameEn: 'White Crème de Cacao', amountMl: 30, amountOz: '1 oz', rawId: 'creme-de-cacao' },
      { name: '新鲜淡奶油', nameEn: 'Fresh Heavy Cream', amountMl: 30, amountOz: '1 oz', rawId: 'heavy-cream' }
    ],
    steps: [
      '在摇酒壶中倒入绿薄荷酒、白可可酒与新鲜淡奶油。',
      '加满方冰，用力摇荡 15 秒至壶外结满浓霜。',
      '双重过滤倒入冷藏至冰凉的碟形香槟杯。',
      '在翠绿色的泡沫表面点缀一片鲜薄荷叶或薄薄一层可可碎。'
    ],
    isIbaCertified: true,
    ibaCategory: 'Contemporary Classics'
  },
  {
    id: 'godfather',
    slug: 'godfather',
    name: '教父',
    nameEn: 'Godfather',
    category: 'contemporary',
    categoryZh: 'IBA 当代经典',
    baseSpirit: 'Whiskey',
    baseSpiritZh: '威士忌',
    flavorProfiles: ['烈酒感', '甜系', '烟熏系'],
    flavorRadar: { sour: 0, sweet: 4, bitter: 1, strong: 5, fruity: 2, herbal: 1 },
    difficulty: 'easy',
    difficultyZh: '简单',
    glass: '古典杯 / Rocks Glass',
    garnish: '压榨橙皮（可选）',
    ice: '大块老冰',
    technique: 'Build',
    techniqueZh: '直调法',
    abv: 33,
    description: '威士忌的刚毅深沉遇上意大利苦杏仁利口酒的温润杏仁甜香，口感丰满圆滑，余韵悠长，致敬马龙·白兰度在《教父》中的沉稳霸气。',
    story: '1970年代随着同名电影《教父》（The Godfather）问世而风靡全球，据称也是影星马龙·白兰度私下最钟爱的饮品之一。',
    proTips: ['经典比例为 1:1 或 2:1，建议使用 50ml 苏格兰/波本威士忌搭配 25ml 迪萨隆诺（Disaronno）杏仁酒以降低过高甜度。'],
    image: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?auto=format&fit=crop&w=800&q=80',
    ingredients: [
      { name: '苏格兰威士忌 (或波本威士忌)', nameEn: 'Scotch Whisky / Bourbon', amountMl: 50, amountOz: '1 2/3 oz', rawId: 'whiskey-scotch' },
      { name: '意大利杏仁利口酒 (Amaretto)', nameEn: 'Amaretto Liqueur', amountMl: 25, amountOz: '3/4 oz', rawId: 'amaretto' }
    ],
    steps: [
      '在古典杯中放入一块整颗老冰。',
      '倒入威士忌与杏仁利口酒。',
      '用吧勺优雅搅拌 20 秒，让冰块轻柔降温稀释。'
    ],
    isIbaCertified: true,
    ibaCategory: 'Contemporary Classics'
  },
  {
    id: 'bellini',
    slug: 'bellini',
    name: '贝利尼',
    nameEn: 'Bellini',
    category: 'contemporary',
    categoryZh: 'IBA 当代经典',
    baseSpirit: 'Liqueur',
    baseSpiritZh: '起泡酒',
    flavorProfiles: ['果香系', '甜系', '清爽系'],
    flavorRadar: { sour: 2, sweet: 4, bitter: 0, strong: 1, fruity: 5, herbal: 0 },
    difficulty: 'easy',
    difficultyZh: '简单',
    glass: '笛形香槟杯 / Flute Glass',
    garnish: '新鲜白桃切片',
    ice: '冰镇原料无需加冰',
    technique: 'Build',
    techniqueZh: '轻柔直调调和法',
    abv: 8,
    description: '威尼斯浪漫的粉红晨曦！新鲜白桃果泥的柔滑香甜与意大利普罗塞克起泡酒的活泼酸度升腾气泡融为一体，果香细腻无与伦比。',
    story: '1948年由威尼斯著名哈利酒吧（Harry\'s Bar）创始人 Giuseppe Cipriani 发明，因其独特粉橙色泽令人联想起文艺复兴画家乔瓦尼·贝利尼的画作。',
    proTips: ['务必选用新鲜白桃泥（White Peach Puree），倒酒时缓慢顺着杯壁注入起泡酒并用吧勺轻微提拉，避免起泡酒过度溢出。'],
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80',
    ingredients: [
      { name: '意大利普罗塞克干型起泡酒', nameEn: 'Prosecco DOC', amountMl: 100, amountOz: '3 1/3 oz', rawId: 'prosecco-champagne' },
      { name: '新鲜白桃果泥', nameEn: 'Fresh White Peach Puree', amountMl: 50, amountOz: '1 2/3 oz', rawId: 'peach-schnapps' }
    ],
    steps: [
      '在冰镇笛形香槟杯中加入 50ml 冷藏白桃果泥。',
      '缓缓倾斜杯身注入 100ml 冰镇普罗塞克起泡酒。',
      '用吧勺轻轻从杯底提拉两次使果泥与气泡酒均匀混合。',
      '杯沿插上一片新鲜白桃薄片装饰。'
    ],
    isIbaCertified: true,
    ibaCategory: 'Contemporary Classics'
  },
  {
    id: 'mimosa',
    slug: 'mimosa',
    name: '含羞草',
    nameEn: 'Mimosa / Buck\'s Fizz',
    category: 'contemporary',
    categoryZh: 'IBA 当代经典',
    baseSpirit: 'Liqueur',
    baseSpiritZh: '香槟起泡酒',
    flavorProfiles: ['柑橘系', '果香系', '清爽系'],
    flavorRadar: { sour: 3, sweet: 3, bitter: 0, strong: 1, fruity: 4, herbal: 0 },
    difficulty: 'easy',
    difficultyZh: '简单',
    glass: '笛形香槟杯 / Flute Glass',
    garnish: '新鲜橙片或草莓',
    ice: '纯冰镇伺服',
    technique: 'Build',
    techniqueZh: '直调法',
    abv: 6,
    description: '全球早午餐（Brunch）无可争议的首席饮品！新鲜现榨橙汁的酸甜多汁与干型香槟的细腻气泡对半调配，金黄耀眼，如盛开的含羞草花。',
    story: '1925年由巴黎丽兹酒店（Hôtel Ritz Paris）首席调酒师 Frank Meier 创造，以黄色花朵含羞草树命名。',
    proTips: ['先倒橙汁后倒香槟，利用碳酸气泡自然对流混合，无需搅拌破坏细腻气泡。'],
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80',
    ingredients: [
      { name: '法国干型香槟 (或普罗塞克)', nameEn: 'Brut Champagne', amountMl: 75, amountOz: '2 1/2 oz', rawId: 'prosecco-champagne' },
      { name: '新鲜现榨甜橙汁 (过滤无渣)', nameEn: 'Fresh Squeezed Orange Juice', amountMl: 75, amountOz: '2 1/2 oz', rawId: 'fresh-orange-juice' }
    ],
    steps: [
      '在冰镇笛形香槟杯中先倒入 75ml 过滤后的冷藏纯橙汁。',
      '缓缓注入 75ml 冰镇干型香槟。',
      '无需搅拌，任由气泡自然上升混合。',
      '在杯缘夹上一片薄橙片装饰。'
    ],
    isIbaCertified: true,
    ibaCategory: 'Contemporary Classics'
  },
  {
    id: 'aperol-spritz',
    slug: 'aperol-spritz',
    name: '阿佩罗斯普利茨',
    nameEn: 'Aperol Spritz',
    category: 'contemporary',
    categoryZh: 'IBA 当代经典',
    baseSpirit: 'Liqueur',
    baseSpiritZh: '利口酒/起泡酒',
    flavorProfiles: ['柑橘系', '苦系', '清爽系'],
    flavorRadar: { sour: 2, sweet: 3, bitter: 2, strong: 1, fruity: 3, herbal: 2 },
    difficulty: 'easy',
    difficultyZh: '简单',
    glass: '古典杯 / Rocks Glass',
    garnish: '新鲜甜橙半月切片',
    ice: '满杯大方冰',
    technique: 'Build',
    techniqueZh: '经典 3-2-1 直调法',
    abv: 11,
    description: '风靡全球的意大利开胃国民酒！3份普罗塞克、2份阿佩罗、1份苏打水，明亮橘红色泽，苦橙草本微苦与气泡清爽在夕阳下绽放。',
    story: '源自奥匈帝国士兵在威尼斯加水饮用葡萄酒的 Spritzen 传统，1950年代与阿佩罗苦酒结合，成为意大利日落时分 Aperitivo 社交文化的灵魂。',
    proTips: ['严格遵循“冰块 -> 普罗塞克 -> 阿佩罗 -> 苏打水”的倒酒顺序，能避免苦酒沉底并最大程度保持气泡。'],
    image: 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?auto=format&fit=crop&w=800&q=80',
    ingredients: [
      { name: '意大利普罗塞克起泡酒', nameEn: 'Prosecco DOC', amountMl: 90, amountOz: '3 oz', rawId: 'prosecco-champagne' },
      { name: '阿佩罗橙味开胃酒', nameEn: 'Aperol', amountMl: 60, amountOz: '2 oz', rawId: 'aperol' },
      { name: '强气泡苏打水', nameEn: 'Club Soda', amountMl: 30, amountOz: '1 oz', rawId: 'club-soda' }
    ],
    steps: [
      '在大型大肚葡萄酒杯中加满大块方冰。',
      '先注入 90ml 冰镇普罗塞克起泡酒。',
      '再环形淋入 60ml 阿佩罗开胃酒。',
      '最后注入 30ml 强气泡苏打水。',
      '放入一片新鲜甜橙切片，轻轻提拉一次。'
    ],
    isIbaCertified: true,
    ibaCategory: 'Contemporary Classics'
  },
  {
    id: 'black-russian',
    slug: 'black-russian',
    name: '黑俄罗斯',
    nameEn: 'Black Russian',
    category: 'contemporary',
    categoryZh: 'IBA 当代经典',
    baseSpirit: 'Vodka',
    baseSpiritZh: '伏特加',
    flavorProfiles: ['烈酒感', '甜系'],
    flavorRadar: { sour: 0, sweet: 4, bitter: 2, strong: 4, fruity: 0, herbal: 1 },
    difficulty: 'easy',
    difficultyZh: '简单',
    glass: '古典杯 / Rocks Glass',
    garnish: '无或马拉斯奇诺樱桃',
    ice: '整块大方冰',
    technique: 'Build',
    techniqueZh: '直调法',
    abv: 30,
    description: '极简主义的醇黑诱惑！高纯度中性伏特加与浓醇甘露咖啡力娇酒 5:2 调配，入口冰凉纯粹，伴随着烘烤咖啡豆与焦糖香草的醇厚余韵。',
    story: '1949年由布鲁塞尔大都会酒店首席调酒师 Gustave Tops 为当时美国驻卢森堡大使 Perle Mesta 特制，正值冷战初期因而得名。',
    proTips: ['在杯顶缓缓淋上一层 30ml 新鲜淡奶油（漂浮不搅拌），即变为著名的白俄罗斯（White Russian）。'],
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
    ingredients: [
      { name: '高纯度伏特加', nameEn: 'Vodka', amountMl: 50, amountOz: '1 2/3 oz', rawId: 'vodka' },
      { name: '甘露咖啡力娇酒', nameEn: 'Kahlúa Coffee Liqueur', amountMl: 20, amountOz: '2/3 oz', rawId: 'kahlua' }
    ],
    steps: [
      '在古典杯中放入大块坚实方冰。',
      '注入伏特加与咖啡力娇酒。',
      '用吧勺轻轻搅拌 15 秒使两者融合降温即可。'
    ],
    isIbaCertified: true,
    ibaCategory: 'Contemporary Classics'
  },
  {
    id: 'white-russian',
    slug: 'white-russian',
    name: '白俄罗斯',
    nameEn: 'White Russian',
    category: 'contemporary',
    categoryZh: '当代流行经典',
    baseSpirit: 'Vodka',
    baseSpiritZh: '伏特加',
    flavorProfiles: ['奶香系', '甜系', '烈酒感'],
    flavorRadar: { sour: 0, sweet: 4, bitter: 1, strong: 3, fruity: 0, herbal: 1 },
    difficulty: 'easy',
    difficultyZh: '简单',
    glass: '古典杯 / Rocks Glass',
    garnish: '表面漂浮 3 颗烘烤咖啡豆',
    ice: '大块老冰',
    technique: 'Float',
    techniqueZh: '漂浮分层法 / 调和',
    abv: 22,
    description: '电影《大保龄离奇绑架》（The Big Lebowski）中督爷（The Dude）的标志灵魂之水！黑咖啡的香醇底色上覆着一层如天鹅绒般丝滑的冰凉鲜奶油。',
    story: '诞生于1960年代中期，在黑俄罗斯配方基础上加入稀奶油，因邪典电影主角全天手持饮用而红遍全球。',
    proTips: ['淡奶油在倒入前稍加轻摇打至微稠，顺着勺背缓慢淋在冰顶，可形成完美的黑白双色大理石分层。'],
    image: 'https://images.unsplash.com/photo-1550985616-10810253b84d?auto=format&fit=crop&w=800&q=80',
    ingredients: [
      { name: '纯净伏特加', nameEn: 'Vodka', amountMl: 50, amountOz: '1 2/3 oz', rawId: 'vodka' },
      { name: '甘露咖啡力娇酒', nameEn: 'Kahlúa Coffee Liqueur', amountMl: 20, amountOz: '2/3 oz', rawId: 'kahlua' },
      { name: '新鲜淡奶油 (或全脂牛奶)', nameEn: 'Fresh Heavy Cream', amountMl: 30, amountOz: '1 oz', rawId: 'heavy-cream' }
    ],
    steps: [
      '在古典杯中加入老冰。',
      '注入伏特加与咖啡力娇酒并简单搅拌。',
      '将吧勺反转贴于液面，缓缓将 30ml 鲜奶油淋在勺背形成顶部白色悬浮奶盖。'
    ],
    isIbaCertified: false
  },
  {
    id: 'irish-coffee',
    slug: 'irish-coffee',
    name: '爱尔兰咖啡',
    nameEn: 'Irish Coffee',
    category: 'contemporary',
    categoryZh: 'IBA 当代经典',
    baseSpirit: 'Whiskey',
    baseSpiritZh: '爱尔兰威士忌',
    flavorProfiles: ['奶香系', '甜系', '烈酒感'],
    flavorRadar: { sour: 0, sweet: 3, bitter: 2, strong: 3, fruity: 1, herbal: 2 },
    difficulty: 'medium',
    difficultyZh: '中等',
    glass: '爱尔兰咖啡杯 / Irish Coffee Glass',
    garnish: '现磨肉豆蔻或现打鲜奶油顶',
    ice: '温热饮品 (Hot Drink)',
    technique: 'Float',
    techniqueZh: '温热调和与奶油漂浮法',
    abv: 14,
    description: '寒冬与雨夜里最温暖的慰藉！滚烫浓郁的黑咖啡与爱尔兰威士忌、粗红糖融为一体，透过顶部冰凉浓稠的鲜奶油缓缓啜饮，冰与火在舌尖交融。',
    story: '1943年爱尔兰福因斯水上飞机基地厨师 Joe Sheridan 为在风雪中被迫折返的疲惫乘客特调，温暖了无数跨大西洋旅客。',
    proTips: ['饮用时切勿搅拌！必须直接大口啜饮，让热咖啡威士忌透过冷奶油层流入唇齿之间。'],
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
    ingredients: [
      { name: '爱尔兰威士忌', nameEn: 'Irish Whiskey', amountMl: 50, amountOz: '1 2/3 oz', rawId: 'whiskey-irish' },
      { name: '新鲜滚烫滴滤黑咖啡', nameEn: 'Hot Fresh Filter Coffee', amountMl: 120, amountOz: '4 oz', rawId: 'espresso' },
      { name: '德梅拉拉黄糖或红糖', nameEn: 'Brown / Demerara Sugar', amountMl: 10, amountOz: '1 tsp', unit: '茶匙', rawId: 'simple-syrup' },
      { name: '微打发冰鲜淡奶油', nameEn: 'Lightly Whipped Heavy Cream', amountMl: 50, amountOz: '1 2/3 oz', rawId: 'heavy-cream' }
    ],
    steps: [
      '用热水温热爱尔兰专用玻璃杯后倒出。',
      '在杯中加入热黑咖啡与红糖，搅拌至糖完全融化。',
      '注入爱尔兰威士忌并再次搅拌均匀。',
      '将淡奶油在摇酒壶中轻摇至可流动但浓稠状态。',
      '反贴吧勺，将冰凉奶油缓缓淋在热咖啡表面形成一层厚厚白盖。'
    ],
    isIbaCertified: true,
    ibaCategory: 'Contemporary Classics'
  },
  {
    id: 'garibaldi',
    slug: 'garibaldi',
    name: '加里波第',
    nameEn: 'Garibaldi',
    category: 'contemporary',
    categoryZh: 'IBA 当代经典',
    baseSpirit: 'Liqueur',
    baseSpiritZh: '金巴利苦酒',
    flavorProfiles: ['柑橘系', '苦系', '清爽系'],
    flavorRadar: { sour: 3, sweet: 3, bitter: 3, strong: 1, fruity: 4, herbal: 2 },
    difficulty: 'easy',
    difficultyZh: '简单',
    glass: '高球杯 / Highball Glass',
    garnish: '新鲜橙轮片',
    ice: '满杯方冰',
    technique: 'Build',
    techniqueZh: '蓬松现榨果汁直调法 (Fluffy Juice)',
    abv: 9,
    description: '象征意大利南北统一的传世之作！北方的金巴利苦酒与南方的西西里甜橙，借助高速破壁产生的“蓬松（Fluffy）”云朵橙汁，展现出惊人的果香与细腻绵密口感。',
    story: '以意大利民族统一英雄朱塞佩·加里波第（Giuseppe Garibaldi）命名，纽约著名酒吧 Dante 将其改良为蓬松果汁版后登顶世界最佳酒吧榜首。',
    proTips: ['使用高速榨汁机现榨橙汁并立即使用，果汁中饱含的微小空气泡会带来如拿铁奶泡般的轻盈质感。'],
    image: 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?auto=format&fit=crop&w=800&q=80',
    ingredients: [
      { name: '金巴利苦酒 (Campari)', nameEn: 'Campari', amountMl: 45, amountOz: '1 1/2 oz', rawId: 'campari' },
      { name: '高速高速现打蓬松甜橙汁', nameEn: 'Fluffy Fresh Orange Juice', amountMl: 120, amountOz: '4 oz', rawId: 'fresh-orange-juice' }
    ],
    steps: [
      '在高球杯中加入方冰。',
      '注入金巴利苦酒。',
      '将新鲜甜橙带皮现切，用高速榨汁机打出充满丰富泡沫的鲜橙汁。',
      '将充满绵密气泡的橙汁直接倾倒入杯顶。',
      '饰以新鲜橙轮片。'
    ],
    isIbaCertified: true,
    ibaCategory: 'Contemporary Classics'
  },
  {
    id: 'americano',
    slug: 'americano',
    name: '美式特调',
    nameEn: 'Americano',
    category: 'classic',
    categoryZh: 'IBA 难忘经典',
    baseSpirit: 'Liqueur',
    baseSpiritZh: '金巴利/红苦艾',
    flavorProfiles: ['草本系', '苦系', '清爽系'],
    flavorRadar: { sour: 1, sweet: 3, bitter: 4, strong: 1, fruity: 2, herbal: 4 },
    difficulty: 'easy',
    difficultyZh: '简单',
    glass: '古典杯 / Rocks Glass',
    garnish: '半月橙片与压榨柠檬皮',
    ice: '满杯方冰',
    technique: 'Build',
    techniqueZh: '直调法',
    abv: 10,
    description: '尼格罗尼（Negroni）的前身！金巴利与甜红苦艾酒等比例混合，注入清爽强劲的苏打水，草本甘苦与气泡跳跃，是意大利午后最惬意的开胃酒。',
    story: '1860年代由 Gaspare Campari 在米兰的 Caffè Campari 发明，因在禁酒令期间极受旅居欧洲的美国游客欢迎而被称为“美式特调”；也是 007 詹姆斯·邦德在小说中点的第一款鸡尾酒。',
    proTips: ['优质的甜红苦艾酒（如 Carpano Antica）与冰镇强气泡苏打水是让这杯低度酒层次跃升的核心。'],
    image: 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?auto=format&fit=crop&w=800&q=80',
    ingredients: [
      { name: '金巴利苦酒 (Campari)', nameEn: 'Campari', amountMl: 30, amountOz: '1 oz', rawId: 'campari' },
      { name: '甜红苦艾酒', nameEn: 'Sweet Vermouth', amountMl: 30, amountOz: '1 oz', rawId: 'sweet-vermouth' },
      { name: '强气泡苏打水 (注顶)', nameEn: 'Club Soda', amountMl: 60, amountOz: '2 oz', rawId: 'club-soda' }
    ],
    steps: [
      '在古典杯中装满冰块。',
      '倒入金巴利与甜红苦艾酒。',
      '注入苏打水并用吧勺轻柔提拉一次。',
      '放入一片半月橙片与柠檬皮卷。'
    ],
    isIbaCertified: true,
    ibaCategory: 'The Unforgettables'
  },

  // ---------------- IBA New Era Drinks 现代新纪元经典 ----------------
  {
    id: 'paper-plane',
    slug: 'paper-plane',
    name: '纸飞机',
    nameEn: 'Paper Plane',
    category: 'new-era',
    categoryZh: 'IBA 新纪元经典',
    baseSpirit: 'Whiskey',
    baseSpiritZh: '波本威士忌',
    flavorProfiles: ['柑橘系', '草本系', '苦系', '果香系'],
    flavorRadar: { sour: 4, sweet: 3, bitter: 2, strong: 3, fruity: 3, herbal: 3 },
    difficulty: 'medium',
    difficultyZh: '中等',
    glass: '碟形香槟杯 / Coupe Glass',
    garnish: '夹在杯缘的小纸飞机（Mini Paper Plane）',
    ice: '摇荡滤冰 (Up)',
    technique: 'Shake',
    techniqueZh: '摇荡法',
    abv: 24,
    description: '21世纪最伟大的现代经典之一！波本威士忌、阿佩罗、诺尼诺草本苦酒与鲜柠檬汁四等分结构，橙红透亮，酸甜草本与木质暖香达成神级平衡。',
    story: '2008年由纽约 Milk & Honey 传奇调酒师 Sam Ross 受 M.I.A. 热门金曲《Paper Planes》启发而创作。',
    proTips: ['诺尼诺苦酒（Amaro Nonino）不可用其他苦酒替代，其格拉帕基底赋予了无与伦比的优雅果香。'],
    image: 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?auto=format&fit=crop&w=800&q=80',
    ingredients: [
      { name: '波本威士忌', nameEn: 'Bourbon Whiskey', amountMl: 22.5, amountOz: '3/4 oz', rawId: 'whiskey-bourbon' },
      { name: '阿佩罗橙味开胃酒', nameEn: 'Aperol', amountMl: 22.5, amountOz: '3/4 oz', rawId: 'aperol' },
      { name: '诺尼诺草本苦酒', nameEn: 'Amaro Nonino Quintessentia', amountMl: 22.5, amountOz: '3/4 oz', rawId: 'amaro-nonino' },
      { name: '新鲜柠檬汁', nameEn: 'Fresh Lemon Juice', amountMl: 22.5, amountOz: '3/4 oz', rawId: 'fresh-lemon-juice' }
    ],
    steps: [
      '在摇酒壶中注入四等分原料。',
      '加满方冰，剧烈摇荡 12-15 秒至极度冰镇。',
      '双重过滤倒入预冷碟形香槟杯或尼克诺拉杯中。',
      '用小木夹在杯缘别上一只折叠的小纸飞机。'
    ],
    isIbaCertified: true,
    ibaCategory: 'New Era Drinks'
  },
  {
    id: 'naked-and-famous',
    slug: 'naked-and-famous',
    name: '赤裸与著名',
    nameEn: 'Naked and Famous',
    category: 'new-era',
    categoryZh: 'IBA 新纪元经典',
    baseSpirit: 'Tequila',
    baseSpiritZh: '梅斯卡尔烟熏酒',
    flavorProfiles: ['烟熏系', '柑橘系', '草本系', '苦系'],
    flavorRadar: { sour: 4, sweet: 3, bitter: 2, strong: 3, fruity: 2, herbal: 4 },
    difficulty: 'medium',
    difficultyZh: '中等',
    glass: '碟形香槟杯 / Coupe Glass',
    garnish: '压榨青柠皮',
    ice: '摇荡滤冰 (Up)',
    technique: 'Shake',
    techniqueZh: '摇荡法',
    abv: 25,
    description: '烟熏与草本的狂想交响曲！梅斯卡尔的浓烈炭火泥土香气、黄查特酒的蜂蜜藏红花、阿佩罗的苦橙与鲜青柠汁四等分交织，极具冲击力。',
    story: '2011年由纽约 Death & Co 著名调酒师 Joaquín Simó 创作，他将其形容为“最后之语与纸飞机的私生子”。',
    proTips: ['选用手工 Artisanal 级 Espadín 梅斯卡尔，搭配 43度的黄查特酒（Yellow Chartreuse），能碰撞出惊艳的烟熏花蜜香气。'],
    image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=800&q=80',
    ingredients: [
      { name: '梅斯卡尔烟熏酒', nameEn: 'Mezcal (Espadín)', amountMl: 22.5, amountOz: '3/4 oz', rawId: 'mezcal' },
      { name: '修道院黄查特酒', nameEn: 'Yellow Chartreuse', amountMl: 22.5, amountOz: '3/4 oz', rawId: 'chartreuse-yellow' },
      { name: '阿佩罗橙味开胃酒', nameEn: 'Aperol', amountMl: 22.5, amountOz: '3/4 oz', rawId: 'aperol' },
      { name: '新鲜青柠汁', nameEn: 'Fresh Lime Juice', amountMl: 22.5, amountOz: '3/4 oz', rawId: 'fresh-lime-juice' }
    ],
    steps: [
      '在摇酒壶中倒入所有等比例原料。',
      '加满冰块，快速强力摇荡 12 秒。',
      '双重过滤倒入预冷碟形杯。'
    ],
    isIbaCertified: true,
    ibaCategory: 'New Era Drinks'
  },
  {
    id: 'gin-basil-smash',
    slug: 'gin-basil-smash',
    name: '金酒罗勒粉碎',
    nameEn: 'Gin Basil Smash',
    category: 'new-era',
    categoryZh: '现代新经典',
    baseSpirit: 'Gin',
    baseSpiritZh: '金酒',
    flavorProfiles: ['草本系', '清爽系', '柑橘系'],
    flavorRadar: { sour: 3, sweet: 3, bitter: 0, strong: 3, fruity: 2, herbal: 5 },
    difficulty: 'medium',
    difficultyZh: '中等',
    glass: '古典杯 / Rocks Glass',
    garnish: '拍醒的新鲜罗勒嫩叶枝顶',
    ice: '满杯大方冰',
    technique: 'Muddle',
    techniqueZh: '捣叶与强力摇荡法',
    abv: 22,
    description: '风靡欧洲大陆的翠绿奇迹！大把新鲜甜罗勒叶在柠檬汁与糖浆中彻底捣碎，释放出震撼眼球的鲜亮翡翠绿色与扑鼻的地中海草本清香。',
    story: '2008年由德国汉堡 Le Lion 酒吧创始人 Joerg Meyer 发明，迅速席卷全球酒吧，成为21世纪欧洲最成功的现代原创鸡尾酒之一。',
    proTips: ['必须毫不吝啬地放入 10-12 片新鲜甜罗勒叶，先与柠檬汁糖浆用力捣压出色，再加冰剧烈摇荡并细网双重过滤。'],
    image: 'https://images.unsplash.com/photo-1527061011665-3652c757a4d4?auto=format&fit=crop&w=800&q=80',
    ingredients: [
      { name: '伦敦干金酒', nameEn: 'London Dry Gin', amountMl: 60, amountOz: '2 oz', rawId: 'gin' },
      { name: '新鲜柠檬汁', nameEn: 'Fresh Lemon Juice', amountMl: 25, amountOz: '3/4 oz', rawId: 'fresh-lemon-juice' },
      { name: '单糖浆', nameEn: 'Simple Syrup', amountMl: 20, amountOz: '2/3 oz', rawId: 'simple-syrup' },
      { name: '新鲜甜罗勒叶', nameEn: 'Fresh Basil Leaves', amountMl: 12, amountOz: '10-12 leaves', unit: '片', rawId: 'fresh-basil' }
    ],
    steps: [
      '在摇酒壶底放入 10~12 片新鲜罗勒叶与柠檬汁、糖浆。',
      '用捣棒（Muddler）用力捣压，直到萃取出浓郁的深绿色汁液。',
      '倒入 60ml 金酒并加满冰块。',
      '剧烈摇荡 15 秒。',
      '使用细滤网（Fine Strainer）双重过滤倒入装满方冰的古典杯中。',
      '在顶部插上拍醒的翠绿鲜罗勒枝。'
    ],
    isIbaCertified: false
  },
  {
    id: 'tommys-margarita',
    slug: 'tommys-margarita',
    name: '托米玛格丽特',
    nameEn: 'Tommy\'s Margarita',
    category: 'new-era',
    categoryZh: 'IBA 新纪元经典',
    baseSpirit: 'Tequila',
    baseSpiritZh: '龙舌兰',
    flavorProfiles: ['柑橘系', '清爽系', '果香系'],
    flavorRadar: { sour: 4, sweet: 2, bitter: 0, strong: 3, fruity: 3, herbal: 2 },
    difficulty: 'easy',
    difficultyZh: '简单',
    glass: '古典杯 / Rocks Glass',
    garnish: '新鲜青柠角与半圈海盐边',
    ice: '大块方冰',
    technique: 'Shake',
    techniqueZh: '摇荡法',
    abv: 24,
    description: '回归龙舌兰本质的现代改良版！去除传统橙酒（君度），直接采用 100% 蓝色龙舌兰蜜（Agave Nectar）作为甜味剂，口感更加纯净、青翠、天然。',
    story: '1990年代初由旧金山 Tommy\'s Mexican Restaurant 老板 Julio Bermejo 创作，被全球调酒界奉为现代龙舌兰纯粹风味的行业金标。',
    proTips: ['选用 100% Blue Agave Reposado（微陈年龙舌兰）能带来更丰满的香草橡木层次。'],
    image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=800&q=80',
    ingredients: [
      { name: '100% 蓝色龙舌兰酒 (Blanco / Reposado)', nameEn: '100% Blue Agave Tequila', amountMl: 60, amountOz: '2 oz', rawId: 'tequila' },
      { name: '新鲜青柠汁', nameEn: 'Fresh Lime Juice', amountMl: 30, amountOz: '1 oz', rawId: 'fresh-lime-juice' },
      { name: '有机龙舌兰蜜 (按 1:1 水稀释)', nameEn: 'Agave Nectar Syrup', amountMl: 15, amountOz: '1/2 oz', rawId: 'agave-nectar' }
    ],
    steps: [
      '古典杯外缘抹半圈细海盐。',
      '在摇酒壶中加入龙舌兰酒、鲜青柠汁与龙舌兰蜜。',
      '加满冰块强力摇荡 12 秒。',
      '过滤倒入装有大方冰的古典杯中，饰以青柠角。'
    ],
    isIbaCertified: true,
    ibaCategory: 'New Era Drinks'
  },
  {
    id: 'bramble',
    slug: 'bramble',
    name: '黑莓荆棘',
    nameEn: 'Bramble',
    category: 'new-era',
    categoryZh: 'IBA 新纪元经典',
    baseSpirit: 'Gin',
    baseSpiritZh: '金酒',
    flavorProfiles: ['果香系', '柑橘系', '清爽系'],
    flavorRadar: { sour: 4, sweet: 3, bitter: 0, strong: 3, fruity: 5, herbal: 2 },
    difficulty: 'medium',
    difficultyZh: '中等',
    glass: '古典杯 / Rocks Glass',
    garnish: '新鲜黑莓两颗与柠檬片',
    ice: '满杯碎冰 (Crushed Ice)',
    technique: 'Float',
    techniqueZh: '摇荡滤入与黑莓利口酒淋面',
    abv: 22,
    description: '英国现代鸡尾酒复兴教父 Dick Bradsell 的传世代表作！金酸酒底倒入堆满白雪般碎冰的杯中，顶部淋下深紫红色黑莓利口酒，如雪原荆棘中渗出的深红浆果汁。',
    story: '1984年由 Dick Bradsell 在伦敦著名的 Fred\'s Club 创作，灵感来自他童年时期在怀特岛采摘野生黑莓的温暖回忆。',
    proTips: ['黑莓利口酒一定要在杯中填满碎冰后最后淋在冰顶，让其缓缓向下渗透呈现大理石晕染效果。'],
    image: 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?auto=format&fit=crop&w=800&q=80',
    ingredients: [
      { name: '伦敦干金酒', nameEn: 'London Dry Gin', amountMl: 50, amountOz: '1 2/3 oz', rawId: 'gin' },
      { name: '新鲜柠檬汁', nameEn: 'Fresh Lemon Juice', amountMl: 30, amountOz: '1 oz', rawId: 'fresh-lemon-juice' },
      { name: '单糖浆', nameEn: 'Simple Syrup', amountMl: 15, amountOz: '1/2 oz', rawId: 'simple-syrup' },
      { name: '黑莓利口酒 (Crème de Mûre)', nameEn: 'Crème de Mûre', amountMl: 15, amountOz: '1/2 oz', rawId: 'creme-de-mure' }
    ],
    steps: [
      '在摇酒壶中加入金酒、新鲜柠檬汁与单糖浆。',
      '加冰摇荡 10 秒。',
      '在古典杯中加满碎冰，将酒液过滤倒入杯中。',
      '用吧勺引流，将 15ml 黑莓利口酒缓慢淋在碎冰表面，形成上紫下透的落日渗染效果。',
      '在冰顶插上新鲜黑莓与柠檬片。'
    ],
    isIbaCertified: true,
    ibaCategory: 'New Era Drinks'
  },
  {
    id: 'trinidad-sour',
    slug: 'trinidad-sour',
    name: '特立尼达酸',
    nameEn: 'Trinidad Sour',
    category: 'new-era',
    categoryZh: 'IBA 新纪元经典',
    baseSpirit: 'Liqueur',
    baseSpiritZh: '安哥斯图拉苦精基底',
    flavorProfiles: ['辛辣系', '草本系', '苦系', '柑橘系'],
    flavorRadar: { sour: 4, sweet: 3, bitter: 5, strong: 4, fruity: 2, herbal: 5 },
    difficulty: 'advanced',
    difficultyZh: '大师级',
    glass: '尼克诺拉杯 / Nick & Nora Glass',
    garnish: '无或压榨橙皮',
    ice: '摇荡滤冰 (Up)',
    technique: 'Shake',
    techniqueZh: '强力摇荡法',
    abv: 28,
    description: '打破一切调酒常规的颠覆性神作！罕见地使用整整 45ml 安哥斯图拉苦精作为核心基酒，与杏仁糖浆、鲜柠檬和黑麦威士忌撞击出惊人的肉桂、丁香、坚果与热带草本酸甜。',
    story: '2009年由纽约 Clover Club 著名调酒师 Giuseppe Gonzalez 创造，凭借不可思议的口感震撼全球鸡尾酒界并入选 IBA 官方名录。',
    proTips: ['由于苦精含有高浓度天然植物精油，必须使用高品质欧洽塔杏仁糖浆（Orgeat）提供足够的油脂甜度与乳化包裹感。'],
    image: 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?auto=format&fit=crop&w=800&q=80',
    ingredients: [
      { name: '安哥斯图拉芳香苦精 (作为主基酒)', nameEn: 'Angostura Aromatic Bitters', amountMl: 45, amountOz: '1 1/2 oz', rawId: 'angostura-bitters' },
      { name: '欧洽塔杏仁糖浆 (Orgeat)', nameEn: 'Orgeat Almond Syrup', amountMl: 30, amountOz: '1 oz', rawId: 'orgeat-syrup' },
      { name: '新鲜柠檬汁', nameEn: 'Fresh Lemon Juice', amountMl: 22.5, amountOz: '3/4 oz', rawId: 'fresh-lemon-juice' },
      { name: '黑麦威士忌 (100 Proof)', nameEn: 'Rye Whiskey', amountMl: 15, amountOz: '1/2 oz', rawId: 'whiskey-rye' }
    ],
    steps: [
      '在摇酒壶中倒入大量安哥斯图拉苦精、杏仁糖浆、柠檬汁与黑麦威士忌。',
      '加入大量方冰，高强度剧烈摇荡 15 秒。',
      '细滤网双重过滤倒入预冷尼克诺拉杯或碟形杯中。'
    ],
    isIbaCertified: true,
    ibaCategory: 'New Era Drinks'
  },
  {
    id: 'new-york-sour',
    slug: 'new-york-sour',
    name: '纽约酸',
    nameEn: 'New York Sour',
    category: 'new-era',
    categoryZh: 'IBA 新纪元经典',
    baseSpirit: 'Whiskey',
    baseSpiritZh: '黑麦/波本威士忌',
    flavorProfiles: ['果香系', '柑橘系', '烈酒感'],
    flavorRadar: { sour: 4, sweet: 3, bitter: 1, strong: 3, fruity: 4, herbal: 2 },
    difficulty: 'medium',
    difficultyZh: '中等',
    glass: '古典杯 / Rocks Glass',
    garnish: '红葡萄酒大理石漂浮层与橙皮',
    ice: '大块方冰',
    technique: 'Float',
    techniqueZh: '摇荡与干红葡萄酒漂浮',
    abv: 22,
    description: '视觉与味觉的双重盛宴！经典威士忌酸的明亮金黄底层上，优雅漂浮着一层深红宝石色的干红葡萄酒，红酒的单宁果酸与波本的香草甜感层层递进。',
    story: '1880年代由芝加哥调酒师首创（当时称 Continental Sour），在曼哈顿酒吧发扬光大后定名为“纽约酸”。',
    proTips: ['漂浮红酒选用酒体饱满、果香浓郁的干红（如西拉 Shiraz、马尔贝克 Malbec 或赤霞珠），顺着勺背轻柔引流。'],
    image: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?auto=format&fit=crop&w=800&q=80',
    ingredients: [
      { name: '黑麦威士忌 (或波本威士忌)', nameEn: 'Rye / Bourbon Whiskey', amountMl: 60, amountOz: '2 oz', rawId: 'whiskey-rye' },
      { name: '新鲜柠檬汁', nameEn: 'Fresh Lemon Juice', amountMl: 30, amountOz: '1 oz', rawId: 'fresh-lemon-juice' },
      { name: '单糖浆', nameEn: 'Simple Syrup', amountMl: 20, amountOz: '2/3 oz', rawId: 'simple-syrup' },
      { name: '新鲜蛋清 (可选)', nameEn: 'Egg White', amountMl: 15, amountOz: '1/2 oz', rawId: 'egg-white' },
      { name: '饱满干红葡萄酒 (漂浮)', nameEn: 'Fruity Dry Red Wine', amountMl: 15, amountOz: '1/2 oz', rawId: 'port-wine' }
    ],
    steps: [
      '在摇酒壶中加入威士忌、柠檬汁与糖浆（若加蛋清可先干摇）。',
      '加满冰块强力摇荡 12 秒。',
      '过滤倒入装有单颗大方冰的古典杯中。',
      '将吧勺反转贴于酒面，缓缓将 15ml 红葡萄酒淋在勺背上形成清晰漂浮分层。'
    ],
    isIbaCertified: true,
    ibaCategory: 'New Era Drinks'
  },
  {
    id: 'porn-star-martini',
    slug: 'porn-star-martini',
    name: '激情马天尼 / 明星马天尼',
    nameEn: 'Porn Star Martini',
    category: 'new-era',
    categoryZh: '当代全球销量冠军',
    baseSpirit: 'Vodka',
    baseSpiritZh: '香草伏特加',
    flavorProfiles: ['果香系', '甜系', '清爽系'],
    flavorRadar: { sour: 3, sweet: 4, bitter: 0, strong: 2, fruity: 5, herbal: 0 },
    difficulty: 'medium',
    difficultyZh: '中等',
    glass: '碟形香槟杯 / Coupe Glass',
    garnish: '半颗漂浮的新鲜百香果与侧边附送的一口干型香槟 (Side shot of Champagne)',
    ice: '摇荡滤冰 (Up)',
    technique: 'Shake',
    techniqueZh: '摇荡法与边射起泡酒伺服',
    abv: 16,
    description: '近二十年来全球英国及欧洲酒吧销量第一的现代超级现象级特调！香草伏特加、百香果利口酒与纯果泥摇出丝绒金黄酒液，搭配一旁冰镇清脆的起泡酒，奢华狂欢。',
    story: '2002年由伦敦著名调酒师 Douglas Ankrah 在 LAB 酒吧创造，他认为这款酒集性感、优雅、自信与狂热于一身。',
    proTips: ['正确喝法：先用勺子吃掉浮在酒面的半颗百香果，喝一口浓郁的马天尼，再啜饮一口清脆干冽的香槟清理味蕾。'],
    image: 'https://images.unsplash.com/photo-1534856966150-c832f7b7a005?auto=format&fit=crop&w=800&q=80',
    ingredients: [
      { name: '香草风味伏特加 (Vanilla Vodka)', nameEn: 'Vanilla Vodka', amountMl: 45, amountOz: '1 1/2 oz', rawId: 'vodka' },
      { name: '百香果利口酒 (Passoã)', nameEn: 'Passoã Passion Fruit Liqueur', amountMl: 15, amountOz: '1/2 oz', rawId: 'passoa' },
      { name: '新鲜百香果泥 / 纯果汁', nameEn: 'Passion Fruit Puree', amountMl: 30, amountOz: '1 oz', rawId: 'passion-fruit-juice' },
      { name: '香草糖浆 (或单糖浆)', nameEn: 'Vanilla Syrup', amountMl: 15, amountOz: '1/2 oz', rawId: 'simple-syrup' },
      { name: '新鲜青柠汁', nameEn: 'Fresh Lime Juice', amountMl: 15, amountOz: '1/2 oz', rawId: 'fresh-lime-juice' },
      { name: '冰镇干型香槟 (分杯侧饮)', nameEn: 'Chilled Brut Champagne', amountMl: 50, amountOz: 'Side Shot (1.5 oz)', rawId: 'prosecco-champagne' }
    ],
    steps: [
      '在摇酒壶中倒入香草伏特加、百香果利口酒、百香果泥、青柠汁与香草糖浆。',
      '加满硬冰块强力摇晃 15 秒至极致起泡。',
      '双重过滤倒入预冷碟形香槟杯。',
      '将半颗切开的新鲜百香果漂浮在酒液中央。',
      '在旁边的 Shot 杯中倒入 50ml 冰镇香槟一同端上。'
    ],
    isIbaCertified: false
  },
  {
    id: 'white-negroni',
    slug: 'white-negroni',
    name: '白尼格罗尼',
    nameEn: 'White Negroni',
    category: 'new-era',
    categoryZh: '当代经典',
    baseSpirit: 'Gin',
    baseSpiritZh: '金酒',
    flavorProfiles: ['草本系', '苦系', '清爽系'],
    flavorRadar: { sour: 0, sweet: 2, bitter: 4, strong: 4, fruity: 2, herbal: 5 },
    difficulty: 'easy',
    difficultyZh: '简单',
    glass: '古典杯 / Rocks Glass',
    garnish: '压榨西柚皮卷 (Grapefruit Twist)',
    ice: '大块老冰',
    technique: 'Stir',
    techniqueZh: '调和法',
    abv: 28,
    description: '尼格罗尼在21世纪最优雅的法式重生！以亮黄色的法国苏兹龙胆草利口酒替代金巴利，以丽叶白开胃酒替代甜红苦艾，草本明亮通透，清爽微苦。',
    story: '2001年由英国调酒师 Wayne Collins 在法国波尔多 Vinexpo 展会期间即兴创作，如今已成为全球顶级鸡尾酒吧的常备金标。',
    proTips: ['西柚皮的清脆柑橘精油与苏兹龙胆草的泥土草本苦味是绝配，用西柚皮代替橙皮风味更惊艳。'],
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80',
    ingredients: [
      { name: '伦敦干金酒', nameEn: 'London Dry Gin', amountMl: 40, amountOz: '1 1/3 oz', rawId: 'gin' },
      { name: '丽叶白开胃酒 (Lillet Blanc)', nameEn: 'Lillet Blanc', amountMl: 30, amountOz: '1 oz', rawId: 'lillet-blanc' },
      { name: '苏兹龙胆草利口酒 (Suze)', nameEn: 'Suze Gentian Liqueur', amountMl: 20, amountOz: '2/3 oz', rawId: 'suze' }
    ],
    steps: [
      '在调酒杯中加入金酒、丽叶白与苏兹苦酒。',
      '加入满杯硬冰块，匀速搅拌 30 秒。',
      '滤入放有大块老冰的古典杯中。',
      '喷挤新鲜西柚皮精油后投入杯中。'
    ],
    isIbaCertified: false
  },

  // ---------------- Tiki 热带传奇殿堂 ----------------
  {
    id: 'zombie',
    slug: 'zombie',
    name: '僵尸',
    nameEn: 'Zombie',
    category: 'classic',
    categoryZh: 'Tiki 传世殿堂',
    baseSpirit: 'Rum',
    baseSpiritZh: '多重朗姆酒',
    flavorProfiles: ['烈酒感', '果香系', '辛辣系', '柑橘系'],
    flavorRadar: { sour: 4, sweet: 4, bitter: 1, strong: 5, fruity: 5, herbal: 3 },
    difficulty: 'advanced',
    difficultyZh: '大师级',
    glass: '柯林杯 / Collins Glass',
    garnish: '薄荷大树冠、凤梨叶、肉桂棒与点火青柠壳',
    ice: '满杯碎冰 (Crushed Ice)',
    technique: 'Shake',
    techniqueZh: '高强度摇荡与碎冰堆叠',
    abv: 35,
    description: 'Tiki 文化的终极狂暴巨作！三种加勒比朗姆酒（含超高度69%火酒）、法勒南香料糖浆、红石榴与苦艾酒精密调配，浓烈狂野，被称为“每人限饮两杯的禁忌之酒”。',
    story: '1934年由 Tiki 文化鼻祖 Don the Beachcomber（唐·埃尔文）在好莱坞酒吧创造，相传一位宿醉客人喝下后声称“自己感觉像个行尸走肉（Zombie）”。',
    proTips: ['融合牙买加高酯朗姆、波多黎各金朗姆与超高度朗姆，搭配一滴苦艾酒与肉桂糖浆，是唐纳德的无价秘方。'],
    image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=800&q=80',
    ingredients: [
      { name: '牙买加深色陈年朗姆', nameEn: 'Aged Jamaican Dark Rum', amountMl: 45, amountOz: '1 1/2 oz', rawId: 'rum-dark' },
      { name: '波多黎各金色朗姆酒', nameEn: 'Gold Puerto Rican Rum', amountMl: 45, amountOz: '1 1/2 oz', rawId: 'rum-white' },
      { name: '超高度深色朗姆酒 (69%-75.5%)', nameEn: 'Overproof Rum (Plantation OFTD / 151)', amountMl: 20, amountOz: '2/3 oz', rawId: 'rum-overproof' },
      { name: '法勒南风味香料糖浆 (Falernum)', nameEn: 'Velvet Falernum', amountMl: 15, amountOz: '1/2 oz', rawId: 'falernum' },
      { name: '新鲜青柠汁', nameEn: 'Fresh Lime Juice', amountMl: 20, amountOz: '2/3 oz', rawId: 'fresh-lime-juice' },
      { name: '西柚汁与肉桂糖浆复合液 (Donn\'s Mix)', nameEn: 'Grapefruit Juice & Cinnamon Syrup', amountMl: 15, amountOz: '1/2 oz', rawId: 'grapefruit-juice' },
      { name: '红石榴糖浆', nameEn: 'Grenadine Syrup', amountMl: 10, amountOz: '1 tsp', rawId: 'grenadine' },
      { name: '苦艾酒 / 绿仙子', nameEn: 'Absinthe', amountMl: 1, amountOz: '2 drops', unit: '滴', rawId: 'absinthe' },
      { name: '安哥斯图拉苦精', nameEn: 'Angostura Bitters', amountMl: 1, amountOz: '1 dash', unit: '滴', rawId: 'angostura-bitters' }
    ],
    steps: [
      '将除超高度朗姆外的所有原料倒入摇酒壶，加入 170g 碎冰。',
      '极速强力摇荡 10 秒。',
      '连同碎冰一同倒入高大的 Tiki 马克杯或柯林杯中。',
      '在杯顶额外加满碎冰，缓缓淋入超高度朗姆酒作为顶部火引。',
      '拍醒一大束鲜薄荷插在冰顶，插上凤梨角与肉桂棒。'
    ],
    isIbaCertified: true,
    ibaCategory: 'New Era Drinks'
  },
  {
    id: 'jungle-bird',
    slug: 'jungle-bird',
    name: '丛林鸟',
    nameEn: 'Jungle Bird',
    category: 'contemporary',
    categoryZh: 'IBA 当代经典',
    baseSpirit: 'Rum',
    baseSpiritZh: '深色黑朗姆',
    flavorProfiles: ['苦系', '果香系', '热带风情', '草本系'],
    flavorRadar: { sour: 3, sweet: 3, bitter: 3, strong: 3, fruity: 4, herbal: 3 },
    difficulty: 'medium',
    difficultyZh: '中等',
    glass: '古典杯 / Rocks Glass',
    garnish: '新鲜菠萝角与三片菠萝叶（如同鸟尾羽毛）',
    ice: '满杯方冰或碎冰',
    technique: 'Shake',
    techniqueZh: '摇荡法',
    abv: 20,
    description: '打破 Tiki 甜腻传统的划时代杰作！牙买加黑朗姆的浓郁糖蜜熟果香，与意大利金巴利苦酒的深沉苦韵在新鲜菠萝汁的丰盈泡沫中达成神妙平衡。',
    story: '1973年诞生于马来西亚吉隆坡希尔顿酒店的 Aviary Bar（鸟舍酒吧），作为宾客入住的欢迎特调，透过玻璃窗即可欣赏花园中的百鸟争鸣。',
    proTips: ['选用重风味的 Blackstrap 糖蜜黑朗姆酒（如 Gosling\'s 或 Cruzan），鲜菠萝汁必须用力摇荡出细腻丰满的泡沫层。'],
    image: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?auto=format&fit=crop&w=800&q=80',
    ingredients: [
      { name: '深色黑朗姆酒 (Blackstrap / Jamaican Dark)', nameEn: 'Dark Rum', amountMl: 45, amountOz: '1 1/2 oz', rawId: 'rum-dark' },
      { name: '金巴利苦酒 (Campari)', nameEn: 'Campari', amountMl: 22.5, amountOz: '3/4 oz', rawId: 'campari' },
      { name: '新鲜菠萝汁', nameEn: 'Fresh Pineapple Juice', amountMl: 45, amountOz: '1 1/2 oz', rawId: 'pineapple-juice' },
      { name: '新鲜青柠汁', nameEn: 'Fresh Lime Juice', amountMl: 15, amountOz: '1/2 oz', rawId: 'fresh-lime-juice' },
      { name: '粗糖浆 (Demerara 2:1)', nameEn: 'Demerara Rich Syrup', amountMl: 15, amountOz: '1/2 oz', rawId: 'simple-syrup' }
    ],
    steps: [
      '在摇酒壶中倒入所有配料与满杯方冰。',
      '剧烈摇晃 15 秒让菠萝汁产生细腻丰满的泡沫。',
      '过滤倒入装满方冰的古典杯或 Tiki 杯中。',
      '在杯缘斜插一块厚切菠萝角与三片挺立的菠萝叶羽冠。'
    ],
    isIbaCertified: true,
    ibaCategory: 'Contemporary Classics'
  },
  {
    id: 'painkiller',
    slug: 'painkiller',
    name: '止痛药',
    nameEn: 'Painkiller',
    category: 'contemporary',
    categoryZh: 'Tiki 海岛传奇',
    baseSpirit: 'Rum',
    baseSpiritZh: '海军朗姆酒',
    flavorProfiles: ['奶香系', '果香系', '甜系'],
    flavorRadar: { sour: 2, sweet: 4, bitter: 0, strong: 3, fruity: 5, herbal: 1 },
    difficulty: 'easy',
    difficultyZh: '简单',
    glass: '飓风杯 / Hurricane Glass',
    garnish: '厚厚现磨肉豆蔻粉、菠萝切片与樱桃',
    ice: '满杯碎冰 (Crushed Ice)',
    technique: 'Shake',
    techniqueZh: '摇荡法',
    abv: 18,
    description: '加勒比海浪与椰风树影的终极写照！深色海军朗姆酒与浓缩椰浆、纯菠萝汁、甜橙汁完美乳化，顶层现磨肉豆蔻辛香扑鼻，治愈一切烦恼。',
    story: '1970年代诞生于英属维尔京群岛约斯特范代克岛上的 Soggy Dollar Bar（湿币酒吧，因客人必须游水上岸弄湿钱包而得名），后被 Pusser\'s 朗姆酒注册为商标。',
    proTips: ['椰子奶油务必使用 Coco López 调酒专用浓缩椰浆，顶层现磨的肉豆蔻粉是这杯酒灵魂级别的嗅觉开关。'],
    image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=800&q=80',
    ingredients: [
      { name: '深色加勒比海军朗姆酒 (如 Pusser\'s)', nameEn: 'Navy Dark Rum', amountMl: 60, amountOz: '2 oz', rawId: 'rum-dark' },
      { name: '纯菠萝汁', nameEn: 'Pineapple Juice', amountMl: 120, amountOz: '4 oz', rawId: 'pineapple-juice' },
      { name: '新鲜甜橙汁', nameEn: 'Fresh Orange Juice', amountMl: 30, amountOz: '1 oz', rawId: 'fresh-orange-juice' },
      { name: '浓缩椰子奶油 (Cream of Coconut)', nameEn: 'Cream of Coconut (Coco López)', amountMl: 30, amountOz: '1 oz', rawId: 'coconut-cream' }
    ],
    steps: [
      '在摇酒壶中倒入朗姆酒、菠萝汁、橙汁与椰子奶油。',
      '加入冰块用力摇晃 15 秒至彻底乳化。',
      '倒入填满碎冰的飓风杯或高球杯中。',
      '在表面大面积现磨新鲜肉豆蔻碎屑，饰以凤梨角。'
    ],
    isIbaCertified: false
  },
  {
    id: 'hurricane',
    slug: 'hurricane',
    name: '飓风',
    nameEn: 'Hurricane',
    category: 'contemporary',
    categoryZh: '新奥尔良狂欢节传奇',
    baseSpirit: 'Rum',
    baseSpiritZh: '深浅朗姆酒',
    flavorProfiles: ['果香系', '柑橘系', '甜系', '烈酒感'],
    flavorRadar: { sour: 3, sweet: 4, bitter: 0, strong: 4, fruity: 5, herbal: 1 },
    difficulty: 'easy',
    difficultyZh: '简单',
    glass: '飓风杯 / Hurricane Glass',
    garnish: '新鲜橙轮片与鸡尾酒红樱桃',
    ice: '满杯碎冰 (Crushed Ice)',
    technique: 'Shake',
    techniqueZh: '摇荡法',
    abv: 22,
    description: '新奥尔良狂欢节（Mardi Gras）的狂暴代名词！深色黑朗姆与白朗姆的强劲酒力被浓郁酸甜的百香果泥、甜橙汁与红石榴糖浆完美包裹，盛在形似防风煤油灯的飓风杯中。',
    story: '二战期间由于威士忌短缺，新奥尔良著名酒吧 Pat O\'Brien\'s 老板为消耗大量强制配给的朗姆酒而创作，如今每年狂欢节售出数以万计。',
    proTips: ['使用真正的新鲜百香果泥而非人工糖浆，能带来纯正爆汁的热带果香与极富穿透力的清爽果酸。'],
    image: 'https://images.unsplash.com/photo-1534856966150-c832f7b7a005?auto=format&fit=crop&w=800&q=80',
    ingredients: [
      { name: '深色黑朗姆酒', nameEn: 'Dark Rum', amountMl: 60, amountOz: '2 oz', rawId: 'rum-dark' },
      { name: '加勒比白朗姆酒', nameEn: 'White Rum', amountMl: 60, amountOz: '2 oz', rawId: 'rum-white' },
      { name: '百香果汁 / 百香果泥', nameEn: 'Passion Fruit Juice / Puree', amountMl: 30, amountOz: '1 oz', rawId: 'passion-fruit-juice' },
      { name: '新鲜甜橙汁', nameEn: 'Fresh Orange Juice', amountMl: 30, amountOz: '1 oz', rawId: 'fresh-orange-juice' },
      { name: '新鲜青柠汁', nameEn: 'Fresh Lime Juice', amountMl: 15, amountOz: '1/2 oz', rawId: 'fresh-lime-juice' },
      { name: '单糖浆', nameEn: 'Simple Syrup', amountMl: 15, amountOz: '1/2 oz', rawId: 'simple-syrup' },
      { name: '红石榴糖浆', nameEn: 'Grenadine Syrup', amountMl: 15, amountOz: '1/2 oz', rawId: 'grenadine' }
    ],
    steps: [
      '在摇酒壶中注入双重朗姆酒、百香果泥、橙汁、青柠汁、单糖浆与红石榴糖浆。',
      '加满冰块强力摇荡 12 秒。',
      '在飓风杯中加满碎冰，过滤倒入酒液。',
      '饰以新鲜橙片与红樱桃。'
    ],
    isIbaCertified: false
  },

  // ---------------- 现代大师 / 世界冠军与亚洲名家 ----------------
  {
    id: 'oaxaca-old-fashioned',
    slug: 'oaxaca-old-fashioned',
    name: '瓦哈卡老式',
    nameEn: 'Oaxaca Old Fashioned',
    category: 'master',
    categoryZh: '现代大师招牌',
    baseSpirit: 'Tequila',
    baseSpiritZh: '龙舌兰/梅斯卡尔',
    flavorProfiles: ['烟熏系', '烈酒感', '草本系', '甜系'],
    flavorRadar: { sour: 0, sweet: 2, bitter: 2, strong: 5, fruity: 2, herbal: 4 },
    difficulty: 'easy',
    difficultyZh: '简单',
    glass: '古典杯 / Rocks Glass',
    garnish: '火烤喷香橙皮 (Flamed Orange Peel)',
    ice: '整块手凿老方冰',
    technique: 'Stir',
    techniqueZh: '调和法',
    abv: 35,
    description: '重新定义现代龙舌兰调酒的划时代之作！微陈 Reposado 龙舌兰的香草橡木遇上瓦哈卡梅斯卡尔的高贵炭火烟熏，在龙舌兰蜜与苦精的烘托下层次登峰造极。',
    story: '2007年由纽约 Death & Co 传奇调酒大师 Phil Ward 创作，开启了全球鸡尾酒吧将梅斯卡尔引入经典框架的伟大风潮。',
    proTips: ['在点缀橙皮时，用火机加热橙皮外侧并向杯中挤压皮油，火焰引燃橙油雾气落在冰块上，赋予焦糖橙香。'],
    image: 'https://images.unsplash.com/photo-1516997121675-4c2d1684aa3e?auto=format&fit=crop&w=800&q=80',
    ingredients: [
      { name: '微陈龙舌兰酒 (Reposado Tequila)', nameEn: 'Reposado Tequila', amountMl: 45, amountOz: '1 1/2 oz', rawId: 'tequila' },
      { name: '瓦哈卡烟熏梅斯卡尔酒 (Mezcal)', nameEn: 'Mezcal', amountMl: 15, amountOz: '1/2 oz', rawId: 'mezcal' },
      { name: '有机龙舌兰蜜糖浆 (2:1)', nameEn: 'Agave Nectar', amountMl: 5, amountOz: '1 tsp', rawId: 'agave-nectar' },
      { name: '安哥斯图拉芳香苦精', nameEn: 'Angostura Bitters', amountMl: 2, amountOz: '2 dashes', unit: '滴', rawId: 'angostura-bitters' }
    ],
    steps: [
      '在古典杯中加入龙舌兰蜜与苦精。',
      '注入微陈龙舌兰与梅斯卡尔酒。',
      '放入大块老冰，用吧勺顺滑搅拌 30 秒。',
      '取大片新鲜橙皮，点燃打火机从上方挤压喷出橙油火焰，将烤香果皮投入杯中。'
    ],
    isIbaCertified: false,
    masterInfo: {
      name: 'Phil Ward',
      quote: '用梅斯卡尔的烟熏灵魂赋予古典鸡尾酒现代重生的力量。',
      bar: 'Death & Co / Mayahuel (纽约)'
    }
  },
  {
    id: 'speak-low',
    slug: 'speak-low',
    name: '低声细语',
    nameEn: 'Speak Low',
    category: 'competition',
    categoryZh: '世界冠军传世作',
    baseSpirit: 'Rum',
    baseSpiritZh: '朗姆酒/雪莉酒',
    flavorProfiles: ['草本系', '烟熏系', '果香系', '甜系'],
    flavorRadar: { sour: 2, sweet: 3, bitter: 2, strong: 3, fruity: 2, herbal: 5 },
    difficulty: 'advanced',
    difficultyZh: '大师级',
    glass: '古典杯 / Rocks Glass',
    garnish: '现筛日本宇治抹茶粉与柚子皮精油',
    ice: '大块老方冰',
    technique: 'Shake',
    techniqueZh: '茶道点茶与摇荡法',
    abv: 22,
    description: '2012 Bacardi Legacy 全球冠军传世酒单！后闲信吾将祖母的日本茶道仪式融入加勒比白朗姆、深色陈酿朗姆与干型菲诺雪莉酒，抹茶的微苦回甘与柚香完美交织。',
    story: '2012年由后闲信吾（Shingo Gokan）代表纽约 Angel\'s Share 参赛并斩获百加得传世鸡尾酒大赛全球总冠军，后成为其在上海创立的亚洲第一酒吧 Speak Low 的同名灵魂酒款。',
    proTips: ['选用日本顶级宇治抹茶粉，先用少量酒液与茶筅化开无颗粒，再加冰剧烈摇荡融合。'],
    image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=800&q=80',
    ingredients: [
      { name: '百加得白朗姆酒', nameEn: 'Bacardí Carta Blanca', amountMl: 30, amountOz: '1 oz', rawId: 'rum-white' },
      { name: '百加得8年陈酿朗姆酒', nameEn: 'Bacardí 8 Años Dark Rum', amountMl: 30, amountOz: '1 oz', rawId: 'rum-dark' },
      { name: '西班牙菲诺雪莉酒 (Fino Sherry)', nameEn: 'Fino Sherry', amountMl: 15, amountOz: '1/2 oz', rawId: 'sherry-fino' },
      { name: '日本宇治高级抹茶粉', nameEn: 'Uji Matcha Green Tea Powder', amountMl: 3, amountOz: '1 tsp', unit: '茶匙' },
      { name: '单糖浆', nameEn: 'Simple Syrup', amountMl: 10, amountOz: '1/3 oz', rawId: 'simple-syrup' }
    ],
    steps: [
      '在摇酒壶底放入 1 茶匙高品质抹茶粉与糖浆、少量白朗姆酒。',
      '用茶筅或吧勺将其彻底打散搅匀至无结块。',
      '加入陈酿黑朗姆、菲诺雪莉酒与大量方冰。',
      '剧烈摇晃 15 秒至极冷并乳化。',
      '细网双重过滤倒入放有手凿老冰的古典杯中。',
      '在冰块表面微筛少量抹茶粉，喷拭日本柚子皮精油。'
    ],
    isIbaCertified: false,
    competitionInfo: {
      name: 'Bacardi Legacy Global Cocktail Competition',
      year: 2012,
      award: 'Global Champion (全球总冠军)',
      bartender: '后闲信吾 (Shingo Gokan)',
      country: 'Japan / USA'
    }
  },
  {
    id: 'bamboo',
    slug: 'bamboo',
    name: '竹子',
    nameEn: 'Bamboo',
    category: 'classic',
    categoryZh: '日式调酒始祖',
    baseSpirit: 'Liqueur',
    baseSpiritZh: '雪莉酒/苦艾酒',
    flavorProfiles: ['草本系', '清爽系', '果香系'],
    flavorRadar: { sour: 1, sweet: 2, bitter: 2, strong: 2, fruity: 2, herbal: 4 },
    difficulty: 'easy',
    difficultyZh: '简单',
    glass: '尼克诺拉杯 / Nick & Nora Glass',
    garnish: '压榨柠檬皮卷',
    ice: '调和滤冰 (Up)',
    technique: 'Stir',
    techniqueZh: '调和法',
    abv: 16,
    description: '日式鸡尾酒历史的开山之作！菲诺雪莉酒的酵母海风与干苦艾酒的优雅草本等比例调和，伴随橙味苦精的轻盈点缀，清透干爽，低酒精度却韵味深长。',
    story: '1890年代由横滨大酒店（Grand Hotel Yokohama）传奇德籍调酒师 Louis Eppinger 创造，成为亚洲调酒史上第一款享誉世界的传世鸡尾酒。',
    proTips: ['必须使用极新鲜的干型菲诺雪莉酒（Fino Sherry）与冷藏干苦艾酒，平稳顺滑搅拌30秒。'],
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=800&q=80',
    ingredients: [
      { name: '干型菲诺雪莉酒 (Fino Sherry)', nameEn: 'Fino Sherry', amountMl: 45, amountOz: '1 1/2 oz', rawId: 'sherry-fino' },
      { name: '干苦艾酒 (Dry Vermouth)', nameEn: 'Dry Vermouth', amountMl: 45, amountOz: '1 1/2 oz', rawId: 'dry-vermouth' },
      { name: '橙味苦精', nameEn: 'Orange Bitters', amountMl: 2, amountOz: '2 dashes', unit: '滴', rawId: 'orange-bitters' },
      { name: '安哥斯图拉芳香苦精', nameEn: 'Angostura Bitters', amountMl: 1, amountOz: '1 dash', unit: '滴', rawId: 'angostura-bitters' }
    ],
    steps: [
      '在调酒杯中加入菲诺雪莉酒、干苦艾酒与双重苦精。',
      '加满冰块，匀速搅拌 30 秒。',
      '滤入冰镇的尼克诺拉杯中。',
      '在酒液表面喷挤柠檬皮精油。'
    ],
    isIbaCertified: false
  },
  {
    id: 'b-52',
    slug: 'b-52',
    name: 'B-52 轰炸机',
    nameEn: 'B-52 Layered Shot',
    category: 'contemporary',
    categoryZh: '经典分层短饮',
    baseSpirit: 'Liqueur',
    baseSpiritZh: '三重利口酒',
    flavorProfiles: ['甜系', '奶香系', '柑橘系'],
    flavorRadar: { sour: 0, sweet: 5, bitter: 1, strong: 3, fruity: 2, herbal: 1 },
    difficulty: 'medium',
    difficultyZh: '中等',
    glass: '子弹杯 / 一口杯 / Shot Glass',
    garnish: '无（清晰三层悬浮大理石界线，可选点火）',
    ice: '常温分层饮用',
    technique: 'Layer',
    techniqueZh: '比重悬浮分层法 (Layering)',
    abv: 27,
    description: '派对狂欢视觉短饮之王！利用不同利口酒的糖度密度差异，在子弹杯中由下至上精准分出黑咖啡、奶油白与金黄甜橙三层清晰界线，一口饮尽风味爆炸。',
    story: '1970年代诞生于加拿大阿尔伯塔省班夫温泉酒店，以美国空军 B-52 长程轰炸机命名。',
    proTips: ['严格按照“甘露咖啡（底层最重） -> 百利甜（中层） -> 柑曼怡/君度（顶层最轻）”的顺序，用吧勺背面贴近液面缓缓引流。'],
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
    ingredients: [
      { name: '甘露咖啡力娇酒 (Kahlúa - 底层)', nameEn: 'Kahlúa Coffee Liqueur', amountMl: 20, amountOz: '2/3 oz', rawId: 'kahlua' },
      { name: '百利甜爱尔兰奶油利口酒 (Baileys - 中层)', nameEn: 'Baileys Irish Cream', amountMl: 20, amountOz: '2/3 oz', rawId: 'baileys' },
      { name: '柑曼怡干邑甜橙酒 (或君度 - 顶层)', nameEn: 'Grand Marnier / Cointreau', amountMl: 20, amountOz: '2/3 oz', rawId: 'grand-marnier' }
    ],
    steps: [
      '在干净直立的子弹杯中先直接注入 20ml 甘露咖啡力娇酒作为底层。',
      '将吧勺反转，勺尖紧贴杯内壁刚漫过咖啡酒液面。',
      '极为缓慢地将 20ml 百利甜顺着吧勺背面淋入，形成中间奶白悬浮层。',
      '同样方式，极其轻缓地将 20ml 柑曼怡橙酒淋在百利甜上方形成顶层金黄透明层。',
      '一饮而尽或插吸管从杯底快速吸饮。'
    ],
    isIbaCertified: false
  },
  {
    id: 'oriental-bamboo',
    slug: 'oriental-bamboo',
    name: '东方竹韵 / 浓香国风',
    nameEn: 'Oriental Bamboo Whisper',
    category: 'signature',
    categoryZh: '新中式国风特调',
    baseSpirit: 'Baijiu',
    baseSpiritZh: '中国白酒',
    flavorProfiles: ['草本系', '果香系', '清爽系', '柑橘系'],
    flavorRadar: { sour: 3, sweet: 3, bitter: 1, strong: 3, fruity: 4, herbal: 4 },
    difficulty: 'medium',
    difficultyZh: '中等',
    glass: '高球杯 / Highball Glass',
    garnish: '新鲜竹叶一片与黄瓜薄带',
    ice: '长条形老冰柱',
    technique: 'Shake',
    techniqueZh: '摇荡与苏打水注顶',
    abv: 16,
    description: '中国纯粮白酒走向世界现代吧台的惊艳之作！浓香型白酒浓郁的窖香、熟菠萝与粮香，在接骨木花利口酒的白花芬芳、鲜青柠与清雅绿茶的调和下化为一缕如竹林听雨般的清爽回甘。',
    story: '新一代中国先锋调酒师致力于将中国传统白酒融入现代鸡尾酒体系的代表作，彻底打破西方对白酒“过烈难调”的固有偏见。',
    proTips: ['选用 52度浓香型白酒（如泸州老窖特曲或开山白酒），浓郁酯香与接骨木花的麝香葡萄花香形成惊人的协同效应。'],
    image: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?auto=format&fit=crop&w=800&q=80',
    ingredients: [
      { name: '中国优质浓香型白酒 (52度)', nameEn: 'Chinese Baijiu (Nongxiang Aroma)', amountMl: 40, amountOz: '1 1/3 oz', rawId: 'baijiu' },
      { name: '圣日耳曼接骨木花利口酒', nameEn: 'St-Germain Elderflower Liqueur', amountMl: 20, amountOz: '2/3 oz', rawId: 'st-germain' },
      { name: '新鲜青柠汁', nameEn: 'Fresh Lime Juice', amountMl: 20, amountOz: '2/3 oz', rawId: 'fresh-lime-juice' },
      { name: '龙井绿茶糖浆 (或单糖浆)', nameEn: 'Longjing Green Tea Syrup', amountMl: 15, amountOz: '1/2 oz', rawId: 'simple-syrup' },
      { name: '强气泡苏打水 (注顶)', nameEn: 'Club Soda', amountMl: 50, amountOz: '1 2/3 oz', rawId: 'club-soda' }
    ],
    steps: [
      '在摇酒壶中倒入白酒、接骨木花利口酒、青柠汁与绿茶糖浆。',
      '加满方冰，剧烈摇荡 12 秒。',
      '在高球杯中放入长条形透明老冰，过滤倒入酒液。',
      '注入冰苏打水至 8 分满，轻柔提拉一次。',
      '贴杯壁插入一片洗净的新鲜竹叶或黄瓜条装饰。'
    ],
    isIbaCertified: false
  }
];
