export const newIngredients = [
  {
    id: 'mezcal',
    slug: 'mezcal',
    name: '梅斯卡尔酒 / 烟熏龙舌兰',
    nameEn: 'Mezcal (Espadín / Artisanal)',
    category: 'base-spirit',
    categoryZh: '基酒',
    abv: 45,
    origin: '墨西哥瓦哈卡州',
    flavorDescription: '以土坑木炭烘烤闷蒸龙舌兰球茎（Piña）后野生发酵蒸馏，带有极其浓烈而迷人的炭火烟熏、泥土、烤龙舌兰草本与矿石咸鲜风味。',
    commonUsage: ['赤裸与著名 (Naked and Famous)', '瓦哈卡老式 (Oaxaca Old Fashioned)', '梅斯卡尔尼格罗尼 (Mezcal Negroni)', '烟熏玛格丽特'],
    buyingGuide: '认准 100% Maguey/Agave 工艺手工梅斯卡尔。入门推荐 Del Maguey Vida、Montelobos Espadín、Illegal Mezcal。',
    storageMethod: '常温避光密封直立保存。',
    image: 'https://images.unsplash.com/photo-1516997121675-4c2d1684aa3e?auto=format&fit=crop&w=600&q=80',
    colorBadge: 'border-emerald-600/40 text-emerald-400'
  },
  {
    id: 'cachaca',
    slug: 'cachaca',
    name: '卡夏莎 / 巴西甘蔗兰姆酒',
    nameEn: 'Cachaça',
    category: 'base-spirit',
    categoryZh: '基酒',
    abv: 40,
    origin: '巴西',
    flavorDescription: '巴西国酒，直接采用新鲜压榨的新鲜甘蔗汁发酵蒸馏而成，具有极其生动鲜明的青草、青苹果、新鲜甘蔗与热带植物鲜甜。',
    commonUsage: ['卡匹林哈 (Caipirinha)', '公鸡尾巴 (Rabo de Galo)', '巴西果香潘趣'],
    buyingGuide: '调酒选用经典未陈酿银色卡夏莎（如 Leblon、Cachaça 51、Ypióca）；纯饮可选巴西本土原生木桶陈酿版。',
    storageMethod: '常温避光保存。',
    image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=600&q=80',
    colorBadge: 'border-lime-500/40 text-lime-400'
  },
  {
    id: 'pisco',
    slug: 'pisco',
    name: '皮斯科白兰地',
    nameEn: 'Pisco (Quebranta / Italia / Acholado)',
    category: 'base-spirit',
    categoryZh: '基酒',
    abv: 40,
    origin: '秘鲁 / 智利',
    flavorDescription: '以纯葡萄汁发酵且单次壶式蒸馏、不得加水降度或木桶陈酿的纯净无色烈酒，最大化保留了白葡萄、茉莉花香、白桃、柑橘皮与干草的鲜灵芬芳。',
    commonUsage: ['皮斯科酸 (Pisco Sour)', '皮斯科潘趣 (Pisco Punch)', '奇尔卡诺 (Chilcano)'],
    buyingGuide: '首选秘鲁法定产区 Quebranta（无芳香型）或 Acholado（调和型），推荐 Barsol Pisco、Caravedo。',
    storageMethod: '常温避光直立保存。',
    image: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?auto=format&fit=crop&w=600&q=80',
    colorBadge: 'border-teal-500/40 text-teal-400'
  },
  {
    id: 'calvados',
    slug: 'calvados',
    name: '卡尔瓦多斯 / 苹果白兰地',
    nameEn: 'Calvados / Apple Brandy',
    category: 'base-spirit',
    categoryZh: '基酒',
    abv: 40,
    origin: '法国诺曼底法定产区',
    flavorDescription: '精选诺曼底数百种专用苹果与梨压榨发酵为西打酒后蒸馏，在橡木桶中陈酿，呈现成熟烤苹果、肉桂、香草、黄油与烘烤坚果的深邃温暖风味。',
    commonUsage: ['寡妇之吻 (Widow\'s Kiss)', '杰克玫瑰 (Jack Rose)', '诺曼底咖啡 (Calvados Coffee)', '秋季老式'],
    buyingGuide: '推荐 AOC Calvados Pays d\'Auge 产区，如 Père Magloire VSOP、Christian Drouin Sélection、Boulard。',
    storageMethod: '常温干燥避光。',
    image: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?auto=format&fit=crop&w=600&q=80',
    colorBadge: 'border-amber-500/40 text-amber-400'
  },
  {
    id: 'whiskey-irish',
    slug: 'whiskey-irish',
    name: '爱尔兰威士忌',
    nameEn: 'Irish Whiskey (Triple Distilled)',
    category: 'base-spirit',
    categoryZh: '基酒',
    abv: 40,
    origin: '爱尔兰',
    flavorDescription: '经过三次壶式蒸馏，不经泥煤熏烤，口感格外柔和顺滑、清脆清爽，伴有青苹果、香草、蜂蜜、燕麦饼干与柔和花香。',
    commonUsage: ['爱尔兰咖啡 (Irish Coffee)', '蒂珀雷里 (Tipperary)', '酸黄瓜回魂 (Pickleback)', '爱尔兰霸王 (Irish Maid)'],
    buyingGuide: '调酒与日常常备：尊美醇 (Jameson)、布什米尔 (Bushmills)、知更鸟 (Redbreast 12年)。',
    storageMethod: '常温避光直立保存。',
    image: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?auto=format&fit=crop&w=600&q=80',
    colorBadge: 'border-emerald-500/40 text-emerald-300'
  },
  {
    id: 'whiskey-japanese',
    slug: 'whiskey-japanese',
    name: '日本威士忌',
    nameEn: 'Japanese Whisky',
    category: 'base-spirit',
    categoryZh: '基酒',
    abv: 43,
    origin: '日本',
    flavorDescription: '借鉴苏格兰传统工艺并在水质、水楢木桶（Mizunara）与调配艺术上达到极致细腻，带有檀香、伽罗熏香、白桃、红苹果与优雅花果香。',
    commonUsage: ['日式高球 (Japanese Highball)', '日式水割 (Mizuwari)', '水楢老式'],
    buyingGuide: '调酒推荐三得利角瓶 (Kakubin)、白州 (Hakushu) 或知多 (Chita)；三得利响 (Hibiki)、山崎 (Yamazaki) 适合品鉴。',
    storageMethod: '常温避光直立保存。',
    image: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?auto=format&fit=crop&w=600&q=80',
    colorBadge: 'border-yellow-600/40 text-yellow-400'
  },
  {
    id: 'rum-overproof',
    slug: 'rum-overproof',
    name: '超高度深色朗姆酒 (Overproof)',
    nameEn: 'Overproof Dark Rum (69% - 75.5% ABV)',
    category: 'base-spirit',
    categoryZh: '基酒',
    abv: 69,
    origin: '牙买加 / 加勒比海',
    flavorDescription: '酒精浓度极高（通常在57%~75.5%），散发极具穿透力的发酵热带熟果酯香（Hogo）、糖蜜、焦糖、肉豆蔻与浓缩香草风味，少许即可点燃整杯酒的香气。',
    commonUsage: ['僵尸 (Zombie)', '迈泰超级版 (Mai Tai Float)', '点火特调 (Flaming Tiki)'],
    buyingGuide: '首选法国干邑名厂调配的 Plantation O.F.T.D. 69% 或 Wray & Nephew 纯白高酯朗姆。',
    storageMethod: '严格常温避光，远离任何火源及明火。',
    image: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?auto=format&fit=crop&w=600&q=80',
    colorBadge: 'border-red-600/40 text-red-500'
  },
  {
    id: 'rhum-agricole',
    slug: 'rhum-agricole',
    name: '农业朗姆酒 (法属西印度群岛)',
    nameEn: 'Rhum Agricole Blanc / Vieux',
    category: 'base-spirit',
    categoryZh: '基酒',
    abv: 50,
    origin: '马提尼克岛 / 瓜德罗普 (AOC 法定产区)',
    flavorDescription: '采用新鲜压榨纯甘蔗汁直接蒸馏，与工业糖蜜朗姆截然不同，带有生机勃勃的青竹、新鲜泥土、割草、白胡椒、柑橘与矿物质芳香。',
    commonUsage: ['小潘趣 (Ti\' Punch)', '法式迈泰 (Mai Tai Agricole)', '代基里进阶版'],
    buyingGuide: '认准马提尼克 AOC 认证，推荐 Clément Blanc 50°、Trois Rivières 或 J.M Blanc。',
    storageMethod: '常温避光直立。',
    image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=600&q=80',
    colorBadge: 'border-lime-600/40 text-lime-400'
  },
  {
    id: 'baijiu',
    slug: 'baijiu',
    name: '中国白酒 (浓香 / 酱香 / 清香)',
    nameEn: 'Chinese Baijiu (Luzhou / Maotai / Fenjiu flavor)',
    category: 'base-spirit',
    categoryZh: '基酒',
    abv: 52,
    origin: '中国 (四川 / 贵州 / 山西)',
    flavorDescription: '采用高粱等纯粮固态发酵与泥窖陈酿蒸馏，蕴含极度复杂的菠萝酯香、熟香蕉、陈年糟香、酱香与粮香，余味绵长悠远，是新中式鸡尾酒的灵魂之笔。',
    commonUsage: ['东方竹语 (Bamboo Whisper)', '北平之秋 (Peking Autumn)', '醉贵妃', '白酒酸 (Baijiu Sour)'],
    buyingGuide: '调酒推荐芳香丰满的浓香型白酒（如泸州老窖特曲、五粮春、开山白酒）或清香爽净的汾酒（青花汾酒/老白汾）。',
    storageMethod: '常温避光直立密封保存。',
    image: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?auto=format&fit=crop&w=600&q=80',
    colorBadge: 'border-red-500/40 text-red-400'
  },
  {
    id: 'prosecco-champagne',
    slug: 'prosecco-champagne',
    name: '干型香槟 / 普罗塞克起泡酒',
    nameEn: 'Brut Champagne / Prosecco DOC',
    category: 'liqueur',
    categoryZh: '配制酒/加度酒',
    abv: 12,
    origin: '法国香槟产区 / 意大利威尼托',
    flavorDescription: '细腻持久的二氧化碳气泡，伴随清脆绿苹果、白梨、柑橘、烤面包和酵母香气，赋予鸡尾酒无可比拟的明亮酸度与欢快升腾感。',
    commonUsage: ['法国75 (French 75)', '阿佩罗斯普利茨 (Aperol Spritz)', '贝利尼 (Bellini)', '含羞草 (Mimosa)', '雨果斯普利茨 (Hugo Spritz)'],
    buyingGuide: '调配 Spritz 选用意大利 Prosecco Brut/Extra Dry；高端调酒选用法国干型香槟 (Moët & Chandon, Veuve Clicquot) 或西班牙 Cava。',
    storageMethod: '避光恒温冷藏，开瓶后使用香槟塞并在24小时内用完以保气泡活性。',
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80',
    colorBadge: 'border-yellow-400/40 text-yellow-300'
  },
  {
    id: 'lillet-blanc',
    slug: 'lillet-blanc',
    name: '丽叶白开胃酒',
    nameEn: 'Lillet Blanc (French Aperitif Wine)',
    category: 'liqueur',
    categoryZh: '配制酒/加度酒',
    abv: 17,
    origin: '法国波尔多',
    flavorDescription: '以85%波尔多白葡萄酒混合15%柑橘与金鸡纳树皮等草本浸泡利口酒调配，散发着蜜饯甜橙、松香、蜂蜜与薄荷的优雅清新香气，微苦回甘。',
    commonUsage: ['维斯帕马天尼 (Vesper Martini)', '除虫剂2号 (Corpse Reviver #2)', '20世纪 (20th Century)', '白尼格罗尼 (White Negroni)'],
    buyingGuide: '法国波尔多原产 Lillet Blanc，经典马天尼变体与开胃酒核心原料。',
    storageMethod: '开瓶后必须冷藏，并在1个月内用完以防氧化变味。',
    image: 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?auto=format&fit=crop&w=600&q=80',
    colorBadge: 'border-yellow-300/40 text-yellow-200'
  },
  {
    id: 'sherry-fino',
    slug: 'sherry-fino',
    name: '菲诺雪莉酒 / 干型雪莉',
    nameEn: 'Fino Sherry / Manzanilla',
    category: 'liqueur',
    categoryZh: '配制酒/加度酒',
    abv: 15,
    origin: '西班牙赫雷斯法定产区 (Jerez)',
    flavorDescription: '在酒花（Flor）保护下陈酿的干型加强白葡萄酒，色泽极浅，口感极干爽，带有独特酵母面团、青橄榄、新鲜扁桃仁与大西洋海风咸香。',
    commonUsage: ['竹子 (Bamboo)', '阿多尼斯 (Adonis)', '低声细语 (Speak Low)', '雪莉高球 (Sherry Cobbler)'],
    buyingGuide: '推荐 Tio Pepe 冈萨雷斯菲诺雪莉酒或 Lustau Puerto Fino。',
    storageMethod: '开瓶后务必冷藏，建议在1周内饮用以保持最高鲜度。',
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=600&q=80',
    colorBadge: 'border-amber-300/40 text-amber-200'
  },
  {
    id: 'port-wine',
    slug: 'port-wine',
    name: '波特酒 (宝石红 / 茶色)',
    nameEn: 'Port Wine (Ruby / Tawny Port)',
    category: 'liqueur',
    categoryZh: '配制酒/加度酒',
    abv: 20,
    origin: '葡萄牙杜罗河谷',
    flavorDescription: '在葡萄发酵中途加入白兰地中止发酵的加强红葡萄酒，保留了充沛天然糖分，饱含成熟黑樱桃、黑莓、李子干、葡萄干、焦糖与黑巧克力香气。',
    commonUsage: ['波特翻转 (Porto Flip)', '主教潘趣 (Bishop Punch)', '暖冬热红酒特调'],
    buyingGuide: '推荐 Taylor\'s (泰勒)、Graham\'s (格拉汉姆) 或 Sandeman 宝石红/茶色波特。',
    storageMethod: '开瓶后冷藏密封，可在1个月内保持稳定风味。',
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=600&q=80',
    colorBadge: 'border-red-900/40 text-red-400'
  },
  {
    id: 'chartreuse-yellow',
    slug: 'chartreuse-yellow',
    name: '修道院黄查特酒',
    nameEn: 'Yellow Chartreuse (Chartreuse Jaune)',
    category: 'liqueur',
    categoryZh: '利口酒',
    abv: 43,
    origin: '法国阿尔卑斯修道院',
    flavorDescription: '相比绿查特酒更柔和、更甜美，添加了藏红花精粹赋予金色色泽，充满蜂蜜、百里香、薄荷、八角、藏红花与柑橘花的馥郁香气。',
    commonUsage: ['赤裸与著名 (Naked and Famous)', '黄色羽翼 (Yellow Daisy)', '寡妇之吻 (Widow\'s Kiss)'],
    buyingGuide: '仅由法国卡尔特会修道院修士依神秘配方手工酿造，是全球殿堂级草本利口酒。',
    storageMethod: '常温避光密封保存。',
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80',
    colorBadge: 'border-yellow-500/40 text-yellow-400'
  },
  {
    id: 'amaro-nonino',
    slug: 'amaro-nonino',
    name: '诺尼诺草本苦酒',
    nameEn: 'Amaro Nonino Quintessentia',
    category: 'liqueur',
    categoryZh: '利口酒',
    abv: 35,
    origin: '意大利弗留利',
    flavorDescription: '以格拉帕白兰地（Grappa）为基底，浸泡龙胆草根、大黄、藏红花、苦橙皮并在小橡木桶陈年，口感丝滑平衡，伴有优雅橙香、焦糖与甘草微苦回甘。',
    commonUsage: ['纸飞机 (Paper Plane)', '黑色曼哈顿 (Black Manhattan)', '餐后纯饮加冰'],
    buyingGuide: '现代经典鸡尾酒“纸飞机”的唯一指定灵魂基石原料，无可替代。',
    storageMethod: '常温避光密封。',
    image: 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?auto=format&fit=crop&w=600&q=80',
    colorBadge: 'border-amber-600/40 text-amber-400'
  },
  {
    id: 'fernet-branca',
    slug: 'fernet-branca',
    name: '费奈·布兰卡草本苦酒',
    nameEn: 'Fernet-Branca',
    category: 'liqueur',
    categoryZh: '利口酒',
    abv: 39,
    origin: '意大利米兰',
    flavorDescription: '全球调酒师的“秘密握手酒”，含有27种来自四大洲的神秘草本（藏红花、没药、甘菊、芦荟等），苦味凌厉霸道，伴随强烈薄荷冰凉感与中药药草芬芳。',
    commonUsage: ['汉基帕基 (Hanky Panky)', '多伦多 (Toronto)', '阿根廷费奈可乐 (Fernet con Coca)'],
    buyingGuide: '认准意大利米兰 Fratelli Branca 原厂出品，经典黑绿磨砂瓶。',
    storageMethod: '常温避光。',
    image: 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?auto=format&fit=crop&w=600&q=80',
    colorBadge: 'border-emerald-800/40 text-emerald-600'
  },
  {
    id: 'suze',
    slug: 'suze',
    name: '苏兹龙胆草利口酒',
    nameEn: 'Suze Gentian Liqueur',
    category: 'liqueur',
    categoryZh: '利口酒',
    abv: 15,
    origin: '法国',
    flavorDescription: '法国传统开胃苦酒，以野生龙胆草根浸泡萃取，呈亮黄色，带有鲜明的泥土根茎、新鲜甘草、柑橘皮与极其持久纯净的清爽草本苦韵。',
    commonUsage: ['白尼格罗尼 (White Negroni)', '苏兹汤力 (Suze Tonic)', '黄色自行车'],
    buyingGuide: '经典法国 Pernod Ricard 旗下 Suze，白尼格罗尼不可或缺的核心。',
    storageMethod: '常温避光。',
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80',
    colorBadge: 'border-yellow-400/40 text-yellow-300'
  },
  {
    id: 'cynar',
    slug: 'cynar',
    name: '朝圣者朝鲜蓟苦酒',
    nameEn: 'Cynar Amaro (Artichoke Liqueur)',
    category: 'liqueur',
    categoryZh: '利口酒',
    abv: 16.5,
    origin: '意大利',
    flavorDescription: '以朝鲜蓟（Artichoke）叶片为主料，混合13种草药与植物提取物制成，深褐色酒液中散发着泥土干草、红茶、黑枣干、甘草与甜美微苦风味。',
    commonUsage: ['朝鲜蓟斯普利茨 (Cynar Spritz)', '苦味老式 (Bitter Giuseppe)', '黑曼哈顿变体'],
    buyingGuide: '意大利 Campari 集团旗下经典 Cynar。',
    storageMethod: '常温避光。',
    image: 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?auto=format&fit=crop&w=600&q=80',
    colorBadge: 'border-amber-800/40 text-amber-600'
  },
  {
    id: 'benedictine',
    slug: 'benedictine',
    name: '法国廊酒 / 修道院草本利口酒',
    nameEn: 'D.O.M. Bénédictine Liqueur',
    category: 'liqueur',
    categoryZh: '利口酒',
    abv: 40,
    origin: '法国诺曼底费康',
    flavorDescription: '由27种精选草本香料（欧当归、牛膝草、杜松子、肉豆蔻、没药、藏红花）经铜壶蒸馏并在橡木桶陈酿，充满温润蜜香、草本与香料深度。',
    commonUsage: ['老广场 (Vieux Carré)', '新加坡司令 (Singapore Sling)', 'B&B (白兰地与廊酒)', '寡妇之吻 (Widow\'s Kiss)'],
    buyingGuide: '认准瓶身上神圣献词印记“D.O.M.”（Deo Optimo Maximo）。',
    storageMethod: '常温避光。',
    image: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?auto=format&fit=crop&w=600&q=80',
    colorBadge: 'border-amber-600/40 text-amber-500'
  },
  {
    id: 'drambuie',
    slug: 'drambuie',
    name: '杜林标蜂蜜威士忌利口酒',
    nameEn: 'Drambuie (Scotch Whisky Liqueur)',
    category: 'liqueur',
    categoryZh: '利口酒',
    abv: 40,
    origin: '苏格兰高地',
    flavorDescription: '以高年份陈年苏格兰单一麦芽威士忌为基底，调和石楠花蜂蜜、草药与秘制香料，口感浓郁华丽，带有石楠花蜜糖、丁香、肉桂与麦芽温暖醇香。',
    commonUsage: ['生锈钉 (Rusty Nail)', '苏格兰咖啡 (Scottish Coffee)', '杜林标高球'],
    buyingGuide: 'William Grant & Sons 旗下经典 Drambuie，生锈钉官方指定原料。',
    storageMethod: '常温保存。',
    image: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?auto=format&fit=crop&w=600&q=80',
    colorBadge: 'border-yellow-600/40 text-yellow-500'
  },
  {
    id: 'grand-marnier',
    slug: 'grand-marnier',
    name: '柑曼怡干邑甜橙酒',
    nameEn: 'Grand Marnier Cordon Rouge',
    category: 'liqueur',
    categoryZh: '利口酒',
    abv: 40,
    origin: '法国',
    flavorDescription: '以法国干邑白兰地为基酒，与加勒比苦橙精油（Citrus Bigaradia）调配并橡木桶陈酿，口感比普通白柑桂更深厚醇美，兼具白兰地陈年木质调与浓郁蜜渍橙皮香。',
    commonUsage: ['凯迪拉克玛格丽特 (Cadillac Margarita)', 'B-52 轰炸机', '金巴利柑曼怡特调', '高端边车 (Grand Sidecar)'],
    buyingGuide: '认准红色绶带与蜡封印章的 Grand Marnier Cordon Rouge 红带。',
    storageMethod: '常温避光。',
    image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=600&q=80',
    colorBadge: 'border-orange-600/40 text-orange-400'
  },
  {
    id: 'creme-de-cacao',
    slug: 'creme-de-cacao',
    name: '白/棕可可利口酒',
    nameEn: 'Crème de Cacao (White & Dark)',
    category: 'liqueur',
    categoryZh: '利口酒',
    abv: 25,
    origin: '法国 / 荷兰',
    flavorDescription: '选用烘烤可可豆与马达加斯加香草浸泡蒸馏而成，白可可酒体透明无色，棕可可呈深褐色，散发纯正黑巧克力、焦糖与香草的丝滑甜美芳香。',
    commonUsage: ['白兰地亚历山大 (Brandy Alexander)', '绿色蚱蜢 (Grasshopper)', '20世纪 (20th Century)', '二十世纪特调'],
    buyingGuide: '制作绿色蚱蜢或20世纪需选用透明的白可可 (White/Blanc)；亚历山大可用棕可可 (Dark/Brown)。推荐 Marie Brizard、Bols、Tempus Fugit。',
    storageMethod: '常温避光。',
    image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=600&q=80',
    colorBadge: 'border-amber-700/40 text-amber-500'
  },
  {
    id: 'creme-de-menthe',
    slug: 'creme-de-menthe',
    name: '绿薄荷利口酒 / 白薄荷利口酒',
    nameEn: 'Crème de Menthe (Green / White)',
    category: 'liqueur',
    categoryZh: '利口酒',
    abv: 24,
    origin: '法国',
    flavorDescription: '采用科西嘉薄荷叶蒸馏提纯，入口具有极其强烈的清凉冰爽感，甜度充沛，带有纯净透彻的天然留兰香与胡椒薄荷精油气息。',
    commonUsage: ['绿色蚱蜢 (Grasshopper)', '毒刺 (Stinger)', '薄荷冰沙特调'],
    buyingGuide: '推荐法国百年品牌 Giffard Menthe Pastille、Bols Green Menthe 或 Marie Brizard。',
    storageMethod: '常温避光。',
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80',
    colorBadge: 'border-emerald-400/40 text-emerald-300'
  },
  {
    id: 'creme-de-violette',
    slug: 'creme-de-violette',
    name: '紫罗兰利口酒',
    nameEn: 'Crème de Violette',
    category: 'liqueur',
    categoryZh: '利口酒',
    abv: 22,
    origin: '奥地利 / 法国阿尔卑斯',
    flavorDescription: '萃取阿尔卑斯野生紫罗兰花朵精粹，具有标志性的梦幻靛紫/天蓝色泽与高雅的花香香水气息，是“飞行”鸡尾酒呈现晨曦天际色彩的灵魂。',
    commonUsage: ['飞行 (Aviation)', '蓝色月亮 (Blue Moon)', '花神马天尼'],
    buyingGuide: '首选奥地利 Rothman & Winter Crème de Violette、Giffard 或 The Bitter Truth。',
    storageMethod: '常温避光保存。',
    image: 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?auto=format&fit=crop&w=600&q=80',
    colorBadge: 'border-purple-500/40 text-purple-400'
  },
  {
    id: 'creme-de-mure',
    slug: 'creme-de-mure',
    name: '黑莓利口酒',
    nameEn: 'Crème de Mûre (Blackberry Liqueur)',
    category: 'liqueur',
    categoryZh: '利口酒',
    abv: 18,
    origin: '法国勃艮第',
    flavorDescription: '采用饱满新鲜野生黑莓浸泡萃取，色泽深红近紫黑，具有浓郁的成熟黑浆果果香、柔和单宁与令人垂涎的莓果酸甜。',
    commonUsage: ['黑莓荆棘 (Bramble)', '黑莓皇家基尔 (Kir Imperial)', '深红金菲士'],
    buyingGuide: '首选法国勃艮第产 Giffard Crème de Mûre、Vedrenne 或 Merlet。',
    storageMethod: '开封后建议冷藏以防果香散逸。',
    image: 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?auto=format&fit=crop&w=600&q=80',
    colorBadge: 'border-purple-800/40 text-purple-600'
  },
  {
    id: 'creme-de-cassis',
    slug: 'creme-de-cassis',
    name: '黑加仑利口酒 / 黑醋栗酒',
    nameEn: 'Crème de Cassis de Dijon',
    category: 'liqueur',
    categoryZh: '利口酒',
    abv: 16,
    origin: '法国勃艮第第戎 (Dijon)',
    flavorDescription: '第戎法定黑醋栗浸渍，色泽如深邃红宝石，充满深厚的高浓度黑醋栗果酱酸甜、紫罗兰花香与天然果皮微涩感。',
    commonUsage: ['基尔 (Kir)', '皇家基尔 (Kir Royale)', '恶魔之角 (El Diablo)', '巴黎人马天尼'],
    buyingGuide: '认准 Cassis de Dijon 法定原产地标志，推荐 Lejay Lagoute 或 Gabriel Boudier。',
    storageMethod: '开封后冷藏保存。',
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=600&q=80',
    colorBadge: 'border-rose-900/40 text-rose-500'
  },
  {
    id: 'passoa',
    slug: 'passoa',
    name: '百香果利口酒',
    nameEn: 'Passoã Passion Fruit Liqueur',
    category: 'liqueur',
    categoryZh: '利口酒',
    abv: 17,
    origin: '法国',
    flavorDescription: '具有高辨识度亮红色泽与浓缩热带百香果汁香气，融合芒果、木瓜与柑橘芬芳，酸甜平衡，果香极具爆破力。',
    commonUsage: ['色情马天尼 / 明星马天尼 (Porn Star Martini)', '百香果斯普利茨', '热带微风'],
    buyingGuide: '明星马天尼指定正宗原料法国原装 Passoã。',
    storageMethod: '常温避光。',
    image: 'https://images.unsplash.com/photo-1534856966150-c832f7b7a005?auto=format&fit=crop&w=600&q=80',
    colorBadge: 'border-red-500/40 text-red-400'
  },
  {
    id: 'peach-schnapps',
    slug: 'peach-schnapps',
    name: '蜜桃利口酒 / 桃味甜酒',
    nameEn: 'Peach Schnapps / Crème de Pêche',
    category: 'liqueur',
    categoryZh: '利口酒',
    abv: 20,
    origin: '荷兰 / 英国 / 美国',
    flavorDescription: '散发极富亲和力的多汁水蜜桃香甜气息，晶莹透明，甜美圆润，是夏日果香系鸡尾酒中最具人气的增甜香氛。',
    commonUsage: ['海滩性爱 (Sex on the Beach)', '毛茸茸的肚脐 (Fuzzy Navel)', '蜜桃冰茶', '贝利尼速配版'],
    buyingGuide: '经典推荐 Archers Peach Schnapps、DeKuyper Peachtree 或 Giffard Crème de Pêche de Vigne。',
    storageMethod: '常温避光。',
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80',
    colorBadge: 'border-pink-400/40 text-pink-300'
  },
  {
    id: 'midori',
    slug: 'midori',
    name: '蜜多丽蜜瓜甜酒',
    nameEn: 'Midori Melon Liqueur',
    category: 'liqueur',
    categoryZh: '利口酒',
    abv: 20,
    origin: '日本 / 法国生产',
    flavorDescription: '以日本夕张蜜瓜和优质网纹甜瓜为原料调配，呈现令人过目难忘的高饱和荧光翠绿色，散发馥郁蜜瓜糖果甜香与清凉果香。',
    commonUsage: ['蜜多丽酸 (Midori Sour)', '日本拖鞋 (Japanese Slipper)', '绿眼怪 (Green Monster)'],
    buyingGuide: '日本三得利旗下原装 Midori，辨识度极高的磨砂浮雕瓶身。',
    storageMethod: '常温避光。',
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80',
    colorBadge: 'border-lime-400/40 text-lime-300'
  },
  {
    id: 'galliano',
    slug: 'galliano',
    name: '加利安诺草本香草利口酒',
    nameEn: 'Galliano L\'Autentico',
    category: 'liqueur',
    categoryZh: '利口酒',
    abv: 42.3,
    origin: '意大利托斯卡纳',
    flavorDescription: '装在如罗马高塔般修长的标志性瓶身中，以地中海茴芹、杜松子、麝香草、薰衣草与马达加斯加香草浸泡，兼具草本辛香与香草甘甜。',
    commonUsage: ['哈维撞墙 (Harvey Wallbanger)', '金色凯迪拉克 (Golden Cadillac)', '金色梦乡 (Golden Dream)'],
    buyingGuide: '务必认准 Galliano L\'Autentico 42.3% 经典原味版。',
    storageMethod: '常温避光。',
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80',
    colorBadge: 'border-yellow-400/40 text-yellow-300'
  },
  {
    id: 'falernum',
    slug: 'falernum',
    name: '法勒南风味糖浆/利口酒',
    nameEn: 'Velvet Falernum / Falernum Syrup',
    category: 'liqueur',
    categoryZh: '利口酒/风味糖浆',
    abv: 11,
    origin: '加勒比巴巴多斯',
    flavorDescription: 'Tiki 鸡尾酒传奇秘方！将青柠皮屑、新鲜生姜、丁香、肉豆蔻与杏仁融合在朗姆酒或蔗糖浆中，散发着无与伦比的热带辛香与青柠酸甜。',
    commonUsage: ['僵尸 (Zombie)', '玉米与石油 (Corn \'n Oil)', '三大洲潘趣', '多诺万特调'],
    buyingGuide: '推荐巴巴多斯原产 John D. Taylor\'s Velvet Falernum 或 Monin / BG Reynolds 法勒南糖浆。',
    storageMethod: '常温避光，开封后建议冷藏。',
    image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=600&q=80',
    colorBadge: 'border-amber-400/40 text-amber-300'
  },
  {
    id: 'heavy-cream',
    slug: 'heavy-cream',
    name: '新鲜淡奶油 / 浓奶油',
    nameEn: 'Heavy Cream / Whipping Cream (35% Fat)',
    category: 'other',
    categoryZh: '乳制品与质感剂',
    abv: 0,
    origin: '法国 / 新西兰',
    flavorDescription: '纯正动物性高脂稀奶油，赋予鸡尾酒丝绸般的绵密天鹅绒触感与温润奶香，能完美包裹可可与烈酒的锋芒。',
    commonUsage: ['白兰地亚历山大 (Brandy Alexander)', '拉莫斯金菲士 (Ramos Gin Fizz)', '绿色蚱蜢 (Grasshopper)', '白俄罗斯 (White Russian)', '爱尔兰咖啡顶层奶盖'],
    buyingGuide: '选用乳脂含量 35% 以上的动物性淡奶油（如安佳 Anchor、铁塔 Elle & Vire、总统 President）。',
    storageMethod: '4°C 冷藏，严禁冷冻，开封后3天内用完。',
    image: 'https://images.unsplash.com/photo-1550985616-10810253b84d?auto=format&fit=crop&w=600&q=80',
    colorBadge: 'border-stone-300/40 text-stone-200'
  },
  {
    id: 'coconut-cream',
    slug: 'coconut-cream',
    name: '椰浆 / 椰子奶油',
    nameEn: 'Cream of Coconut (Coco López / Real)',
    category: 'other',
    categoryZh: '辅料与质感剂',
    abv: 0,
    origin: '波多黎各 / 东南亚',
    flavorDescription: '加糖浓缩椰肉奶油，质地浓稠厚重如炼乳，带有浓郁馥郁的烘烤椰子甜香与油脂滑顺感，是 Tiki 热带鸡尾酒的灵魂之源。',
    commonUsage: ['椰林飘香 (Piña Colada)', '止痛药 (Painkiller)', '热带椰香莫吉托'],
    buyingGuide: '认准调酒专用的 Cream of Coconut（推荐 Coco López 或 Reàl Coconut Cream），切勿误买无糖淡椰浆 (Coconut Milk)。',
    storageMethod: '常温避光保存，开罐后冷藏并在1周内用完。',
    image: 'https://images.unsplash.com/photo-1534856966150-c832f7b7a005?auto=format&fit=crop&w=600&q=80',
    colorBadge: 'border-neutral-300/40 text-neutral-200'
  },
  {
    id: 'espresso',
    slug: 'espresso',
    name: '意式浓缩咖啡 / 冷萃浓缩液',
    nameEn: 'Fresh Espresso / Cold Brew Concentrate',
    category: 'mixer',
    categoryZh: '咖啡与汽水辅料',
    abv: 0,
    origin: '意大利 / 全球通用',
    flavorDescription: '高压萃取的极浓咖啡液，表面覆盖金黄色咖啡油脂沫（Crema），兼具烘焙焦香、黑巧克力苦甜与细腻果酸，摇荡后能产生细腻持久的奶泡层。',
    commonUsage: ['浓缩咖啡马天尼 (Espresso Martini)', '爱尔兰咖啡 (Irish Coffee)', '咖啡汤力 (Coffee Tonic)'],
    buyingGuide: '首选意式咖啡机现萃的双份意式浓缩 (Double Espresso)；亦可用高浓度冷萃浓缩液代替。',
    storageMethod: '现萃现用，稍冷却后加入摇酒壶以防迅速融化冰块。',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80',
    colorBadge: 'border-stone-700/40 text-stone-400'
  },
  {
    id: 'fresh-basil',
    slug: 'fresh-basil',
    name: '新鲜甜罗勒叶',
    nameEn: 'Fresh Sweet Basil Leaves',
    category: 'garnish',
    categoryZh: '装饰与香草',
    abv: 0,
    origin: '地中海 / 亚洲',
    flavorDescription: '散发着胡椒、丁香、茴香与清凉青草香气的鲜嫩绿叶，经杵臼轻压可释放出令人震撼的鲜绿叶绿素与草本清香。',
    commonUsage: ['金酒罗勒粉碎 (Gin Basil Smash)', '罗勒金汤力', '草本莫吉托'],
    buyingGuide: '选用叶片饱满翠绿、无黑斑的甜罗勒（Sweet Basil）。',
    storageMethod: '茎部插入水中常温保存，或用微湿厨房纸包裹冷藏。',
    image: 'https://images.unsplash.com/photo-1527061011665-3652c757a4d4?auto=format&fit=crop&w=600&q=80',
    colorBadge: 'border-emerald-500/40 text-emerald-400'
  },
  {
    id: 'cocktail-onion',
    slug: 'cocktail-onion',
    name: '珍珠洋葱 / 鸡尾酒小洋葱',
    nameEn: 'Cocktail Silverskin Onion',
    category: 'garnish',
    categoryZh: '装饰与香草',
    abv: 0,
    origin: '欧洲 / 荷兰',
    flavorDescription: '经过微酸盐水浸渍的去皮银皮小洋葱，爽脆多汁，带有淡淡的甜咸与香醋微酸，是吉普森（Gibson）鸡尾酒唯一的标志性灵魂装饰。',
    commonUsage: ['吉普森 (Gibson)', '洋葱干马天尼'],
    buyingGuide: '选用进口罐装鸡尾酒珍珠洋葱 (Cocktail Silverskin Onions)。',
    storageMethod: '浸泡在原汤盐水中冷藏。',
    image: 'https://images.unsplash.com/photo-1575023782549-62ca0d244b39?auto=format&fit=crop&w=600&q=80',
    colorBadge: 'border-zinc-400/40 text-zinc-300'
  },
  {
    id: 'orange-flower-water',
    slug: 'orange-flower-water',
    name: '天然橙花水',
    nameEn: 'Orange Flower Water (Eau de Fleur d\'Oranger)',
    category: 'other',
    categoryZh: '芳香精萃与调味液',
    abv: 0,
    origin: '法国格拉斯 / 黎巴嫩',
    flavorDescription: '由苦橙花瓣蒸馏提取的天然植物花露，极富穿透力的高雅白花香氛，仅需2-3滴即可为整杯酒带来如梦似幻的春日柑橘花林香气。',
    commonUsage: ['拉莫斯金菲士 (Ramos Gin Fizz)', '新奥尔良菲士', '花香金汤力'],
    buyingGuide: '首选法国 Cortas 或 A. Monteux 纯天然蒸馏橙花水。',
    storageMethod: '常温避光密封。',
    image: 'https://images.unsplash.com/photo-1527061011665-3652c757a4d4?auto=format&fit=crop&w=600&q=80',
    colorBadge: 'border-orange-300/40 text-orange-200'
  }
];
